readmeio/rdme

- lib/push.js
Since the content type was application/x-www-form-urlencoded, the body-parser size limit for json wasn't being applied, so even small swagger files were being blocked.
> Send as json instead of application/x-www-form-urlencoded

- lib/docs/index.js
- test/docs.test.js
Prior to this, it would console.log `[undefined]` which isn't great!
> Add message when a doc hasn't been updated

- lib/swagger.js
- package.json
- test/swagger.test.js
This makes the OAS argument of `rdme swagger` optional. If one is not supplied, we will now attempt to locate a `(swagger|openapi).(json|yaml)` file in the directory that `rdme swagger` is being run within. If one is then not found, we'll now point the user in the direction of using `rdme oas init` to get started down the path to spec creation.
I've also fixed a minor bug where if you supplied an incorrect API key to `rdme swagger`, we will now fail with a clearer error message than "There was an error uploading!".
> If an OAS is not supplied, attempt to discover one in the root dir.

- cmds/docs/edit.js
- cmds/docs/index.js
- cmds/login.js
- cmds/logout.js
- cmds/oas.js
- cmds/open.js
- cmds/swagger.js
- cmds/versions/create.js
- cmds/versions/delete.js
- cmds/versions/index.js
- cmds/versions/update.js
- cmds/whoami.js
- lib/commands.js
- lib/help.js
- test/cli.test.js
- test/cmds/docs.test.js
- test/cmds/login.test.js
- test/cmds/logout.test.js
- test/cmds/open.test.js
- test/cmds/swagger.test.js
- test/cmds/versions.test.js
- test/cmds/whoami.test.js
- test/lib/commands.test.js
This adds two new commands: 
- `rdme logout` - Logs the current user out and clears their saved config file.
- `rdme whoami` - Returns the email and project of the user that's currently logged in.
I also did a few minor maintenancey things to clean some things up from https://github.com/readmeio/rdme/pull/49:
- Renaming the `weight` property in commands to `position`. Since our new `help` screen shows the split groups, the weight is really more of a position declaration in that screen now so I've renamed it to reflect that. It still works the same, this is just purely renaming the property so it's clearer what it represents.
- Making our test descriptions `describe('...' () => {})` consistent.
> Adding new authentication oriented commands

- cmds/swagger.js
- package-lock.json
Add header to tell ReadMe that the synced file is coming from the cli
> Add x-readme-source header

- .github/workflows/nodejs.yml
- package.json
Support for Node 8 ended at the start of the year so there's no reason for us to continue targeting it.
> feat: drop support for node 8

- cmds/open.js
- cmds/swagger.js
- package-lock.json
- package.json
- test/cli.test.js
- test/cmds/docs.test.js
- test/cmds/login.test.js
- test/cmds/open.test.js
- test/cmds/swagger.test.js
> chore(deps-dev): upgrading jest to v25

- README.md
We should really just set up a redirect for all of our readme.readme.io links... but in the meantime...
> docs: Fix link to ReadMe API docs

- cmds/versions/create.js
- lib/prompts.js
This resolves a strange issue with Enquirer where it wouldn't properly skip the `newVersion` question when creating a new version. 
Resolves https://github.com/readmeio/rdme/issues/206
> fix: setting initial data for newVersion when creating a version

- cmds/docs/edit.js
- cmds/docs/index.js
- cmds/login.js
- cmds/swagger.js
- cmds/versions/create.js
- cmds/versions/delete.js
- cmds/versions/index.js
- cmds/versions/update.js
- lib/apiError.js
- rdme.js
- test/cmds/docs.test.js
- test/cmds/login.test.js
- test/cmds/swagger.test.js
- test/cmds/versions.test.js
- test/lib/apiError.test.js
This overhauls every command to support the new way we're handling errors within the API and allowing us to surface Metrics log IDs in the console for API failures
> feat: overhauling error handling to support the new api error responses

- src/cmds/openapi.js
Our API sometimes has trouble with 1.5MB+ OpenAPI files during upload with the request timing out and returning an invalid payload through our API. When this happens rdme will surface an "There was an error uploading!" error which isn't helpful.
Instead, we're now looking for these timeouts and returning a contextual error about it with a suggestion to help get the file uploaded. Obviously it'd be better if our API didn't have these pitfalls, but it's a gigantic project to rework that backend to not have these issues.
Upload the file attached in https://github.com/readmeio/rdme/issues/84#issuecomment-858369838, it should timeout and throw this new error message I've added here.
> fix: catch upload timeouts and return a better error message

- src/lib/help.js
This fixes some improper `Array.sort()` logic within the help screen where the `position` properties that each command emits weren't being properly utilized.
Before:
After:
> fix: command position sorting within the help screen

- __tests__/.eslintrc
- __tests__/__fixtures__/existing-docs/subdir/another-doc.md
- __tests__/cmds/docs.test.js
- src/cmds/docs/index.js
> feat: making the docs command recursive by default

- __tests__/cmds/docs.test.js
- __tests__/cmds/versions.test.js
- __tests__/index.test.js
- src/cmds/docs/edit.js
- src/cmds/docs/index.js
- src/cmds/openapi.js
- src/cmds/versions/delete.js
- src/cmds/versions/update.js
- src/lib/prompts.js
- src/lib/versionSelect.js
We had the option to select an existing version or create a new version with the openapi command if no version argument was provided, this PR adds that to all the commands that require the version argument.
- Adds version selection to the relevant docs and version commands
- Allows for specifying whether the user should receive the option to create a new version or just gives them a list of their current versions to choose from.
> feat: add version selection to all relevant commands

- __tests__/__fixtures__/slug-docs/new-doc-slug.md
- __tests__/cmds/docs.test.js
- src/cmds/docs/index.js
Coinbase was running into an issue where pages were getting new slugs instead of updating the existing ones. They added a `slug` field in their metadata in the markdown files, which it seems like we didn't officially support. Since we were using the file name to generate the slug when seeing if a doc existed or not, but still created the page with the slug they defined it was ending up in a weird state where pages were being created on every sync. 
If you want to test locally you can run the following:
```
./rdme/bin/rdme docs ~/path/to/markdown --key KEY --version 1.0
```
This will update the page here: https://dash.readme.com/project/PROJECT/v1.0/docs/new-page
```
---
title: "New Page"
slug: "new-page"
category: "CATEGORY ID"
---
Look at that slug. 🐌 (not a slug, but the best I can do) …
```
> fix: allow customers to define the slug in the metadata

- .github/dependabot.yml
- README.md
- __tests__/index.test.js
- bin/rdme
- package-lock.json
- package.json
- src/cmds/docs/index.js
- src/cmds/login.js
- src/cmds/open.js
- src/cmds/openapi.js
- src/cmds/swagger.js
- src/cmds/versions/index.js
- src/cmds/whoami.js
- src/index.js
- src/lib/help.js
This swaps out the [colors](https://npm.im/colors) library for [chalk](https://npm.im/chalk). `chalk` is a drop-in replacement for `colors`.
Why? 
1. `chalk` has a lot more dev support than `colors`.
2. I've always loathed how `colors` works by modifying `String.prototype`. Sure you can load `colors/safe` to do `colors.green()` but that's not the default flow.
3. `oas-normalize` and its dependency on `@readme/openapi-parser` uses it by way of `@readme/better-ajv-parser` so loading in `colors` here for yet another way of colorizing CLI messaging is silly.
4. We've been inconsistent in how we load it in the files that do have colors, so often you'll see `text.green` and it only works because that command is loaded in `./bin/rdme` where `require('colors')` was present. Woof.
5. It's got …
> feat: swapping out the colors library for chalk

- __tests__/__fixtures__/swagger-with-invalid-extensions.json
- __tests__/__snapshots__/index.test.js.snap
- __tests__/cmds/__snapshots__/validate.test.js.snap
- __tests__/cmds/openapi.test.js
- __tests__/cmds/validate.test.js
- src/cmds/validate.js
This adds a new `rdme validate` command that can either take a file to validate or like `rdme openapi` search the local filesystem for a file matching `/(swagger|openapi).(json|yaml)/` to validate instead.
Resolves https://github.com/readmeio/rdme/issues/326.
Here's what the command looks like in action:
> feat: adding a new `validate` command for validating API definitions

- README.md
- __tests__/cmds/versions.test.js
- src/cmds/versions/index.js
Updates the `--raw` option so it outputs a JSON object rather than a JS object. Resolves #369.
See tests! You can also check this branch out locally and run commands like:
```sh
bin/rdme versions --raw | jq
```
and do filtering with something like:
```sh
bin/rdme versions --raw | jq '.[] | select(.is_stable == true)'
```
> feat(versions): stringify JSON for `--raw` option

- __tests__/__snapshots__/index.test.js.snap
- __tests__/cmds/openapi.test.js
- __tests__/index.test.js
- src/cmds/openapi.js
- src/cmds/swagger.js
> docs: add/improve our command warnings

- .github/workflows/ci.yml
Since rdme doesn't have any peerDependencies we don't need >= npm@7 in CI. 
If all tests are still all passing then this is good to go.
> ci: drop the npm@7 requirement before installing deps in ci

- __tests__/cmds/openapi.test.js
- bin/rdme
- src/cmds/openapi.js
- src/index.js
Turns out we had an edge case where we were returning a `console.log()` rather than a rejected `Promise` when we received errors from the API, resulting in an incorrectly successful exit code. This PR fixes that in https://github.com/readmeio/rdme/pull/409/commits/0f2372ed1fc0b94ddba546a5a162b35297c0444b so we properly return an exit code of 1. And as expected, some housekeeping:
Resolves #407.
If the tests pass, we should be good! But as an extra check, you can check out this branch and run the following commands to confirm that we see a non-zero exit code:
```sh
$ bin/rdme openapi --id="asdf" --key="asdf" ./__tests__/__fixtures__/ref-oas/petstore.json
We couldn't find your API key.
If you need help, email support@readme.io and include the following link to your API log: …
```
> fix(openapi): return rejected `Promise` if spec uploads fail

- .eslintrc
- bin/rdme
Does CI pass with no warnings?
**EDIT:** [yes](https://github.com/readmeio/rdme/runs/4745002939?check_suite_focus=true#step:5:12)
> ci: tweak ESLint config, small refactors

- bin/rdme
- package-lock.json
- package.json
Add update-notifier to warn when using an old version of rdme
Example of what it looks like:
To test this out, you can replace the line in bin/rdme with the following:
```
updateNotifier({ pkg: { name: 'rdme', version: '1.0.0' }, updateCheckInterval: 0 }).notify();
```
Example nabbed from here:
https://github.com/yeoman/update-notifier/blob/HEAD/example.js
> feat: add update-notifier to warn when using an old version of rdme

- README.md
No actual content changes here, just running this through VS Code's Markdown formatter so subsequent docs changes are easier to read.
Also I fixed some broken links in the TOC, but I'm honestly unsure if we should still keep it since [GitHub now renders this natively for README.md files](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/).
> docs: run VSCode formatter, fix TOC

- .github/workflows/gh-action-simple.yml
- CONTRIBUTING.md
Local GitHub Action testing is an extremely useful tool for debugging our repo now, so I figure I should document it.
> docs: add contributing guidelines

- __tests__/lib/fetch.test.js
- src/cmds/openapi.js
- src/lib/fetch.js
Refactors and enhances our `fetch` wrapper to add the `x-readme-source` header to all requests (the value defaults to `cli`). If it's in a GitHub Actions environment, it'll set that header to `cli-gh`.
Additionally, if in a GitHub Actions environment, it'll capture certain attributes about the environment and include that in the request headers as well. You can read more about all the environmental variables available to us here: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
Do tests pass? Alternatively you can go to our project's Metrics dashboard, filter for requests using the `rdme-test` project's API key, and confirm the headers show up there (at least in the most recent requests after this PR was opened) 🎉
> feat: add GitHub-specific request headers

- .github/workflows/ci.yml
- .github/workflows/gh-action-simple.yml
- bin/rdme
- package-lock.json
- package.json
- src/cmds/docs/edit.js
- src/cmds/docs/index.js
- src/cmds/login.js
- src/cmds/logout.js
- src/cmds/oas.js
- src/cmds/open.js
- src/cmds/openapi.js
- src/cmds/swagger.js
- src/cmds/validate.js
- src/cmds/versions/create.js
- src/cmds/versions/delete.js
- src/cmds/versions/index.js
- src/cmds/versions/update.js
- src/cmds/whoami.js
- src/index.js
- src/lib/fetch.js
- src/lib/isGitHub.js
- src/lib/logger.js
<details>
<summary><b>Commands that now have debugging</b></summary>
</details>
<details>
<summary><b>Helper functions that now have debugging</b></summary>
Obviously there are many other helper functions, but these are the only ones that felt necessary.
</details>
Additionally, I made a small enhancement to `bin/rdme` to output errors via the native GitHub Action annotation format so they're properly surfaced. You can see an example of this in [this workflow run](https://github.com/readmeio/rdme/actions/runs/1890909393) (and in the image below[^1]).
No functional changes beyond migrating `isGHA()` into its own file and enhancing the logging in `bin/rdme` (the results of which you can see in the annotation example above). Do tests pass? And can you see debug logs on [this workflow …
> feat: debugging support

- __tests__/__fixtures__/relative-ref-oas/components/external-components.json
- __tests__/__fixtures__/relative-ref-oas/petstore.json
- __tests__/__snapshots__/index.test.js.snap
- __tests__/cmds/__snapshots__/openapi.test.js.snap
- __tests__/cmds/openapi.test.js
- __tests__/cmds/validate.test.js
- src/cmds/openapi.js
- src/cmds/validate.js
We use a monorepo structure to manage our projects and our OpenAPI specification contains relative references to external models.
So when running `rdme` on our repository, we need to specify the current working directory to handle those relative paths.
This PR adds an optional `workdir` parameter to the `openapi` command.
To test it, you have to run the `openapi` command using the `--workdir=path`.
So all file should be relative to the specified `path`.
> feat: add workdir arg to openapi command

- README.md
- __tests__/__fixtures__/relative-ref-oas/petstore.json
- __tests__/__snapshots__/index.test.js.snap
- __tests__/cmds/__snapshots__/openapi.test.js.snap
- __tests__/cmds/openapi.test.js
- __tests__/cmds/validate.test.js
- src/cmds/openapi.js
- src/cmds/validate.js
Follow-up to #450 with some minor copy and documentation changes for the (newly-renamed) `--workingDirectory` option.
Do the docs and naming conventions look good? And do tests pass?
> docs(openapi): update working directory usage

- .github/workflows/docs.yml
- README.md
- __tests__/lib/getNodeVersion.test.js
- bin/set-version-output
- documentation/rdme.md
- package.json
- src/lib/getNodeVersion.js
This is a doozy. This PR updates our README.md, adds docs for [our knowledge base](https://docs.readme.com/docs/rdme), and sets up a CI workflow for doing a find/replace and syncing the knowledge base page to ReadMe.
Fixes RM-3553
> docs: add GitHub Actions guidance

- .eslintrc
- .github/workflows/ci.yml
- bin/rdme
- package-lock.json
- package.json
- src/lib/apiError.js
- src/lib/prompts.js
> ⚠️ Do not merge this until the new Github Action workflow has been tagged to the current v6 release series.
Node 12 hits EOL in April and with our new action in #437 it'd be nice to start with a clean start, breaking change for folks, so we might as well drop support for Node 12 now and publish a breaking change rather than having to publish another breaking change in a few months. 
This also allows us to _finally_ start using optional chaining in this codebase as that was introduced in Node 14.
> feat: dropping support for node 12

- __tests__/cmds/docs.test.js
- src/cmds/docs/index.js
Realized while working on the docs syncing workflow in #439 that this would be a super easy win and extremely useful to have.
If tests pass, we should be good to go! You can also try this out yourself on any project by checking out this branch and running the following command: 
```sh
bin/rdme docs --dryRun --key=API_KEY __tests__/__fixtures__/new-docs
```
This won't make any changes in your project and instead will return a command output that looks like this:
```
🎭 dry run! This will create 'new-doc' with contents from __tests__/__fixtures__/new-docs/new-doc.md with the following metadata: {"category":"5ae122e10fdf4e39bb34db6f","title":"This is the document title"}
```
> feat(docs): add `--dryRun` option

- action.yml
Noticed https://github.com/readmeio/rdme/pull/459 and decided to bump that in our action. Not sure if it does anything 🤷🏽‍♂️ 
If the [GitHub Action Dry Run part of CI](https://github.com/readmeio/rdme/runs/5383759437?check_suite_focus=true) passes, we should be good to go!
> chore(deps): bump to setup-node v3 in action

- __tests__/cmds/openapi.test.js
- src/cmds/openapi.js
The `token` parameter has been deprecated for some time now, so this PR removes it from the `openapi` command (targeting v7).
Do tests pass?
> chore: remove deprecated `token` parameter

- README.md
- documentation/legacy-github-action.md
- documentation/rdme.md
Closes https://github.com/readmeio/rdme/issues/467
Just doc updates, so feel free to just gloss everything over! If you're curious about the actual diff in the Markdown syncing example, see this commit: b2966f18e1fe93cbfb0d96a842d2e3ae3b050859
> docs(GHA): small updates

- __tests__/cmds/__snapshots__/validate.test.js.snap
- __tests__/cmds/openapi.test.js
- documentation/rdme.md
- src/cmds/openapi.js
- src/cmds/validate.js
- src/lib/prepareOas.js
| 🚥 Fix RM-3999 |
| :-- |
When running the `openapi` command successfully, we now include the path to the OpenAPI definition in the success message, as well more tailored messaging for OpenAPI vs. Swagger definitions.
Do the refactors look good? And do tests pass?
> feat(openapi): specify spec path and type in success response

- package-lock.json
- package.json
Bumps `@readme/oas-examples`, `eslint`, and `prettier` to their latest releases.
> chore(deps-dev): bumping out of date dev deps

- bin/set-version-output
- package.json
> fix: our broken set-version-output script

- .github/workflows/ci.yml
- package-lock.json
- package.json
This updates our `engines` requirement to allow installs on Node 17 without npm showing a warning about it being unsupported.
The Node 17 CI workflow should be passing just fine and not emitting any errors or warnings during the `npm ci` phase.
> feat: extending support to node 17

- documentation/rdme.md
Some user feedback, this suggested edit: https://dash.readme.com/project/developers/v2.0/suggested/update/6255ac0b9fb776009ecdc2e6
Do these updates make sense?
> docs(`docs`): clarify slug handling

- __tests__/bin.test.js
- bin/rdme
| 🚥 Fix RM-4182 |
| :-- |
Our "sorry your Node version is unsupported" error message has two `v`'s in it because `process.version` contains one already.
```
> process.version
'v14.19.1'
```
> fix: unsupported version error message having double "v"s

- .github/workflows/ci.yml
- __tests__/lib/isSupportedNodeVersion.test.js
- package-lock.json
- package.json
- src/lib/getNodeVersion.js
Node 18 hit GM yesterday so we need to support it.
Instead of changing our `engines` requirements to be inclusive we're now going to allow Node 14+, and going forward will revise this when LTS releases get EOL'd.
Tests on Node 18 should be passing.
> feat: adding support for node 18

- src/cmds/openapi.js
The API key is logged as part of normal operation, which is not a good idea.
| 🚥 Fix RM-XXX |
| :-- |
Describe in detail what this PR is for.
> Don't log API Key

- .github/dependabot.yml
- __tests__/cmds/openapi.test.js
- package-lock.json
- package.json
- src/cmds/openapi.js
- src/lib/logger.js
- src/lib/prepareOas.js
- src/lib/streamSpecToRegistry.js
| 🚥 Fix RM-4367 |
| :-- |
_(hopefully) fixes #499_ 
<details>
<summary><b>Previous TODOs (archived)</b></summary>
</details>
Do tests pass? You can also test this command with a project of your own by checking out this branch and running:
```sh
bin/rdme openapi __tests__/__fixtures__/ref-oas/petstore.json --key=<api key>
```
[^1]: I did a lot of test coverage/cleanup work as part of these changes, but that blew up the diff and scope of this PR so any changes unrelated to this new `openapi` process can be found in [#520](https://github.com/readmeio/rdme/pull/520).
> perf(openapi): upload improvements

- .github/workflows/ci.yml
Per [GitHub's docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), "by default, a workflow only runs when a `pull_request` event's activity type is `opened`, [`synchronize`](https://github.community/t/what-is-a-pull-request-synchronize-event/14784), or `reopened`".
This should hopefully get tests running for [outside contributors](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks).
Do tests continue to run properly?
> ci: run tests on `pull_request` event

- README.md
- __tests__/cmds/docs.test.js
- src/cmds/docs/create.js
- src/cmds/docs/single.js
| 🚥 Fix RM-XXX |
| :-- |
- add doc:create command to allow a single markdown file to be synced rather than only supporting an entire directory.
- updated markdown and doc test to reflect changes
The `doc:create` command can be ran with the `--filepath` attribute being set to a specific markdown file-path and that file will be synced. If the slug already exists then the chance will not be merged.
> feat: add `docs:single`

- config/custom-environment-variables.json
- config/default.js
Per internal discussion, this adds env variable support for setting the `host` and `hub` config variables.
Confirmed that the `config.host` value is updated properly when passing in the `README_HOST` env variable:
> feat(config): add ability to override host + hub

- __tests__/cmds/openapi.test.js
- package-lock.json
- package.json
- src/cmds/openapi.js
- src/lib/fetch.js
| 🚥 Fix RM-4868 |
| :-- |
Right now, if we receive an error response from the API when running the `openapi` command, we have some not-so-great error handling where if the response body isn't JSON, we basically just write it off as a timeout error: https://github.com/readmeio/rdme/blob/862d4009257ddbbc553cbe67fe8a4ebb1b7bec7c/src/cmds/openapi.js#L111-L129
Our debug logs in this situation aren't helpful either: since we blindly use `res.json()` to parse the response body, our debug logs consistently return an unhelpful `Unexpected token < in JSON` error.
In this PR, our approach to parsing the response from our API has been improved to better allow us to understand non-JSON response bodies. We now do some smarter inspection of the response to determine whether or not it's a timeout. It …
> feat: better error-handling for non-JSON responses

- __tests__/cmds/docs.test.js
- src/cmds/docs/index.js
- src/cmds/docs/single.js
- src/lib/fetch.js
- src/lib/pushDoc.js
Follow-up to #529. Consolidates our docs create/update logic into a single function. This should set up future functionality (e.g. Custom Pages, Changelog) more easily.
Tests haven't changed at all, so if those pass then we should be good to go!
> refactor(docs): consolidate logic

- __tests__/lib/commands.test.js
- bin/rdme
- src/cmds/categories/create.js
- src/cmds/categories/index.js
- src/cmds/changelogs/index.js
- src/cmds/changelogs/single.js
- src/cmds/docs/edit.js
- src/cmds/docs/index.js
- src/cmds/docs/single.js
- src/cmds/login.js
- src/cmds/logout.js
- src/cmds/oas.js
- src/cmds/open.js
- src/cmds/openapi.js
- src/cmds/validate.js
- src/cmds/versions/create.js
- src/cmds/versions/delete.js
- src/cmds/versions/index.js
- src/cmds/versions/update.js
- src/cmds/whoami.js
- src/lib/commands.js
- src/lib/help.js
| 🚥 Fix RM-4913 |
| :-- |
Per feedback from Jon, renames a field our `Command` class from `category` to `cmdCategory`. It's a bit confusing given the "category" terminology in the ReadMe and `rdme` ecosystem.
Also made a tiny ESLint disable change in our `bin/rdme` file—see https://github.com/readmeio/rdme/commit/3fbf38f45bb3212d1efa65ab76f09ed7fa22033e for the reasoning.
I ran any commands that I think would be affected (e.g. `bin/rdme`, `bin/rdme openapi --help`, etc.) and tests are passing now... our test suite is pretty comprehensive so I can't think of anything else that would break, but fingers crossed 😬
> refactor: rename `category` to `cmdCategory` in `Command` class

- .github/workflows/retag-release.yaml
- bin/retag-release.js
| 🚥 Fix RM-4840 |
| :-- |
The **rdme** GitHub Action required people to write workflows with the line `uses: readmeio/rdme@1.2.3` but GitHub's convention is for action versions to be tagged `v1.2.3`. Because of this some users have written `uses: readme/rdme@v1.2.3` and of course they expect that to work.
This workflow looks for releases created with a tag like `1.2.3` and adds a second tag like `v1.2.3`. It uses [actions/github-script](https://github.com/actions/github-script) which is the simplest way to run a short script in a GitHub workflow. There were some existing third-party actions for adding a tag to a repo, but I didn't really want to rely on a third-party script for something so simple. (Admittedly this was going to be a one-liner but with input validation and HTTP error …
> feat: add retag-release workflow to add a vX.Y.Z tag for our GitHub Action

- __tests__/cmds/changelogs.test.js
- __tests__/cmds/custompages.test.js
- __tests__/cmds/docs.test.js
- src/cmds/changelogs/index.js
- src/cmds/changelogs/single.js
- src/cmds/custompages/index.js
- src/cmds/custompages/single.js
- src/cmds/docs/index.js
- src/cmds/docs/single.js
| 🚥 Fix #546  |
| :-- |
Fixes an issue where our single commands had faulty conditional logic and therefore weren't working on `.markdown` files properly.
Also leans up a few tests, see https://github.com/readmeio/rdme/commit/21ba907ca774230366ff2fee6d872babe02137ef
Do the test changes look good and do they pass?
> fix(docs/single): support files with `.markdown` extension

- src/cmds/openapi.js
- src/cmds/validate.js
- src/lib/prepareOas.js
| 🚥 Fix RM-XXX |
| :-- |
Combines the file-searching logic (i.e. auto-detection of `openapi.json`, `swagger.yml`, etc.) from the `validate` and `openapi` commands and puts it in our `prepareOas` helper function. That function signature has changed a bit to handle that shared logic a bit better. I also refactored the `openapi` command to have a flow that is easier to follow.
These changes are setting up the updates coming in RM-4898 and RM-4984.
Might help to hide whitespace for this review! No changes were made to tests and no functional changes are happening so if all tests pass we should be good to go.
> refactor(openapi): DRY and logic reorg

- package-lock.json
- package.json
- src/.sink.d.ts
- src/lib/prepareOas.ts
- tsconfig.json
I rewrote [oas-normalize](https://npm.im/oas-normalize) last night in TypeScript (https://github.com/readmeio/oas-normalize/pull/210) so we no longer need to have a typing sinkhole exclusion for it.
> feat: upgrading oas-normalize to pull in its new TS typings

- .github/workflows/ci.yml
- .github/workflows/docs.yml
Are tests still running on every push to the PR, but with fewer duplicate workflow runs? And is [the docs syncing workflow](https://github.com/readmeio/rdme/runs/7775815962?check_suite_focus=true) running as expected and properly skipping over the actual syncing step?
> ci: optimize test runs and add docs syncing dry run

- action.yml
As part of #560, we [added a `build` step](https://github.com/readmeio/rdme/pull/560/commits/bee05e6a558e672271bae2132b6726084d5ccb99) when setting up the GitHub Actions environment. But this in turn made the logs a bit noisy:
This makes a small update to our Actions workflow so we're not outputting `tsc` build logs that the user doesn't need to know about:
I also added `--no-save` to our `npm install` step since there's no point in updating the lockfile. Not sure if it's faster to do this vs. `npm ci`. At some point it might be cool to look into caching our dependencies but this seems okay for now.
Do the GitHub Action dry runs continue to run as expected? And do the logs look cleaner?
> fix: quieter log outputs when installing GHA

- CONTRIBUTING.md
- __tests__/cmds/__snapshots__/login.test.ts.snap
- __tests__/cmds/login.test.ts
- __tests__/cmds/openapi.test.ts
- __tests__/cmds/versions/create.test.ts
- __tests__/cmds/versions/update.test.ts
- __tests__/lib/prompts.test.ts
- package-lock.json
- package.json
- src/cmds/login.ts
- src/cmds/openapi.ts
- src/cmds/versions/create.ts
- src/cmds/versions/delete.ts
- src/cmds/versions/update.ts
- src/lib/baseCommand.ts
- src/lib/prepareOas.ts
- src/lib/promptWrapper.ts
- src/lib/prompts.ts
- src/lib/versionSelect.ts
| 🚥 Fix RM-5116 |
| :-- |
Migrating our prompts system from the universally-disliked [`enquirer`](https://github.com/enquirer/enquirer) to [`prompts`](https://github.com/terkelg/prompts). In addition to it being a far better from a DX and testing standpoint, we also get a few nice helpful cues from `prompts` when a user is required to take an action (note the grayed out "use arrow-keys" guidance):
Overall, the prompt object patterns are fairly similar and there shouldn't be a whole lot of material changes for users (except in maybe the `login` command since that was previously using the ancient [`read`](https://npm.im/read) package).
All areas of `rdme` that use a prompts-based system have been migrated over, namely:
Because this work got me looking into commands that don't get a lot of …
> refactor: migrate from `enquirer` to `prompts`

- __tests__/cmds/login.test.ts
- src/cmds/categories/create.ts
- src/cmds/categories/index.ts
- src/cmds/changelogs/index.ts
- src/cmds/changelogs/single.ts
- src/cmds/custompages/index.ts
- src/cmds/custompages/single.ts
- src/cmds/docs/edit.ts
- src/cmds/docs/index.ts
- src/cmds/docs/single.ts
- src/cmds/login.ts
- src/cmds/openapi/index.ts
- src/cmds/versions/create.ts
- src/cmds/versions/delete.ts
- src/cmds/versions/index.ts
- src/cmds/versions/update.ts
- src/lib/baseCommand.ts
- src/lib/promptWrapper.ts
| 🚥 Fix RM-3621 (and a bunch of other stuff) |
| :-- |
Tests appear to pass, but it might be good to check out this branch, run the build, and try messing around.
[^1]: You can test this by prefixing any command with a [CI env variable](https://github.com/npm/ci-detect/blob/main/lib/index.js). I've been running `GITLAB_CI=true bin/rdme login`
> chore(prompt): various enhancements and refactors

- README.md
- __tests__/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/index.test.ts
- src/cmds/openapi/index.ts
| 🚥 Fix RM-5148 |
| :-- |
Adds a `--create` flag to the `openapi` command so users can bypass the prompt that asks them whether or not they want to create or update a spec.
See tests.
> feat(openapi): add `--create` flag

- .github/workflows/ci.yml
- README.md
- __tests__/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/index.test.ts
- src/cmds/openapi/index.ts
Today when using the `rdme openapi <path> --version=<version>` command to update a spec file (selecting `Update` in the first prompt), we're prompted for selecting an API spec file, even if there's only a single one present.
This PR adds the `--updateSingleSpec` option that will instruct the CLI to not prompt the user if there's only a single spec file available, and choose it automatically.
1. Start with a clean project with no API spec files at all
2. Run `rdme openapi <path> --version=<version>`, which will upload the file without any create/update prompt because there's nothing to update.
3. Run `rdme openapi <path> --version=<version>` once again, and select `update` in the first prompt and expect to see another prompt with a single option.
4. Abort the previous command.
5. Run `rdme …
> feat(openapi): Add `updateSingleSpec` option to automatically update an only available spec file without any prompts

- __tests__/cmds/openapi/index.test.ts
- __tests__/helpers/get-api-mock.ts
- src/cmds/openapi/index.ts
Continuing the work from #584 by ensuring our test bed has really good `x-readme-version` header checks. Turns out, there was a tiny bug discovered! Thanks tests.
Do tests pass?
> fix(openapi): stricter tests, `create` flag edge case

- packages/create/package.json
Per [the `npm init` docs](https://docs.npmjs.com/cli/v8/commands/npm-init), we can utilize the `@readme` namespace to do fancy things like:
```sh
npm init @readme
```
which would run the following:
```sh
npx @readme/create
```
This PR creates that `@readme/create` repo and aliases it to `rdme openapi --github`, but we might wanna do something fancier at some point. Also should this be versioned the same as `rdme`? Lots of open questions, but figured I'd open this PR to get the conversation started.
> feat: `npm init` alias

- README.md
- __tests__/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/index.test.ts
- src/cmds/openapi/index.ts
| 🚥 Fix RM-5419 |
| :-- |
Chatted with a customer who wants to programmatically grab the `id` from the `openapi` command output. Figured this would be a nice win to sneak into v8.
Any other attributes that you think would be helpful to include in the JSON object? And do tests pass?
> feat(openapi): raw command output option

- src/lib/pushDoc.ts
- src/lib/readDoc.ts
Was thinking through ideas for future improvements and noticed some weird patterns. This just refactors them to be a bit more readable and well-documented so future improvements will be a bit easier.
No end results should be different—if tests pass we should be good!
> refactor(docs): internal command signatures

- __tests__/cmds/changelogs/index.test.ts
- __tests__/cmds/changelogs/single.test.ts
- __tests__/cmds/custompages/index.test.ts
- __tests__/cmds/custompages/single.test.ts
- __tests__/cmds/docs/index.test.ts
- __tests__/cmds/docs/single.test.ts
- src/lib/fetch.ts
- src/lib/pushDoc.ts
We render the doc ID in the success response for the `docs`/`changelogs`/`custompages` commands. Issue is that we were using `res.id` when we should be using `res._id`, since only the latter actually shows up for Changelog and Custom Pages.
Do tests pass?
> fix(docs): use correct `_id` param

- README.md
- __tests__/cmds/__snapshots__/login.test.ts.snap
- __tests__/cmds/login.test.ts
- src/cmds/login.ts
| 🚥 Fix RM-5498 |
| :-- |
The `--2fa` flag that's required to log in with `rdme` is clunky. Now that we've overhauled our prompts system, it was stupidly easy to add a flow that goes something like this:
1. User logs in with username and password
1. API returns a 401 with the `LOGIN_TWOFACTOR` code, meaning the user forgot to include a 2FA code
1. `rdme` checks for the `LOGIN_TWOFACTOR` code. In that case, it prompts the user for the token and sends another login request with the token![^1]
By removing the `2fa` flag in the `rdme` client, the login flow is infinitely more smooth. The other great thing is that this requires no changes to our API, so we can maintain backwards compatibility with older versions of `rdme`.
This PR also includes some minor testbed housekeeping as well.
Do these …
> feat(breaking/login): remove `2fa` flag in favor of better prompts

- __tests__/cmds/openapi/index.test.ts
- __tests__/lib/prompts.test.ts
- src/cmds/categories/create.ts
- src/cmds/categories/index.ts
- src/cmds/docs/edit.ts
- src/cmds/docs/index.ts
- src/cmds/docs/single.ts
- src/cmds/openapi/index.ts
- src/cmds/versions/delete.ts
- src/cmds/versions/update.ts
- src/lib/prompts.ts
- src/lib/versionSelect.ts
When going through some of the prompts for the `openapi` command, I realize we have the following question in the prompt flow:
```
? Would you like to use an existing project version or create a new one? › - Use arrow-keys. Return to submit.
❯   Use existing
Create a new version
```
It feels like an unlikely scenario where a user will want to create a new version when running this command. And upon further investigation, we do this for a few other commands for which it makes even less sense to ask this question:
- `categories`: if you're trying to list the categories for a project version, why would you want to create a new version just to list the categories in that newly created version?
- `docs:edit`: if you're trying to edit an existing document, why would you want to create a new …
> feat(breaking): drop version creation question from prompt flows

- .github/workflows/ci.yml
Node 19 was released yesterday so though our `engines` field allows Node >=14, we should still make sure we're able to be run on it.
> ci: run tests against node 19

- __tests__/cmds/docs/edit.test.ts
- __tests__/index.test.ts
- __tests__/lib/__snapshots__/commands.test.ts.snap
- src/cmds/docs/edit.ts
| 🚥 Fix RM-5649 |
| :-- |
Per [this discussion](https://github.com/readmeio/rdme/pull/644#discussion_r1006261908), `docs:edit` is now deprecated.
Does the warning look good? And do tests pass?
> feat(breaking/docs): deprecate `docs:edit`

- README.md
- __tests__/cmds/docs/index.test.ts
- __tests__/cmds/docs/prune.test.ts
- __tests__/index.test.ts
- __tests__/lib/__snapshots__/commands.test.ts.snap
- src/cmds/guides/index.ts
- src/cmds/guides/prune.ts
- src/cmds/index.ts
- src/lib/commands.ts
| 🚥 Fix RM-5581 |
| :-- |
Adds an alias for the `docs` family of commands called `guides`, as well as some corresponding documentation touch-ups. Note that the `docs:edit` command doesn't have a corresponding alias since that command is now deprecated (see https://github.com/readmeio/rdme/pull/646).
Does the alias'ing approach + the corresponding docs look good?
> feat(docs): add `guides` alias

- README.md
- __tests__/cmds/docs/prune.test.ts
- src/cmds/docs/prune.ts
Add `--noPrompt` flag to the `docs:prune` command
1. Manually add a document to your project in the UI.
2. Run the `docs:prune` command as is, see that it asks for confirmation before deleting the document.
3. Run again but with `--noPrompt` and see that the document is deleted from the project.
> feat(docs:prune): `--confirm` flag to bypass prompt

- package.json
Apparently `tags` isn't a thing in [the package.json spec](https://docs.npmjs.com/cli/v8/configuring-npm/package-json), which seems to be the reason why our keywords aren't showing up on npm: https://www.npmjs.com/package/rdme
> fix: package.json keywords declarations

- __tests__/lib/createGHA.test.ts
- src/lib/createGHA/index.ts
Tightening our requirements for executing the GitHub Actions prompt: now, a user *must* have a GitHub remote for their repo in order for the ask to be made. We've had a few issues related to this prompt running when it shouldn't, so this should hopefully reduce the likelihood of a false positive.
Do tests pass?
> fix(createGHA): remove non-github remote check

- package-lock.json
- package.json
Upgrades `oas-normalize` to fix a problem with Postman to OpenAPI conversions where we weren't replacing variables, leading to server URLs containing variables getting corrupted and losing a lot of data.
https://github.com/readmeio/oas-normalize/pull/229
> fix: upgrade oas-normalize to fix a postman conversion issue

- .github/workflows/ci.yml
- __tests__/lib/fetch.test.ts
- package-lock.json
- package.json
- src/lib/isCI.ts
I opened https://github.com/npm/ci-detect/issues/47 to address this, but per #664 it looks like our CI detection has some imperfections. [`ci-info`](https://github.com/watson/ci-info) seems to be more popular and well-maintained. We looked at this package ages ago but I was initially hesitant because it is a bit annoying to write tests with it but I got that figured out.
**Update**: it looks like the npm CLI team [is planning on deprecating their package in favor of `ci-info`](https://github.com/watson/ci-info/pull/95#issue-1444551786), so we should probably do this anyways.
No material changes here except perhaps better CI detection. Do tests pass?
> fix: swap out `@npmcli/ci-detect` for `ci-info`

- __tests__/cmds/docs/index.test.ts
- __tests__/cmds/open.test.ts
- __tests__/cmds/openapi/index.test.ts
- src/lib/versionSelect.ts
Since simplifying our version selection flow in https://github.com/readmeio/rdme/pull/635, the version selection prompt annoyingly prompts the user to select a version even if only one exists in ReadMe:
https://user-images.githubusercontent.com/8854718/202499667-f42f5c98-a2f2-40b2-b667-659074abd877.mp4
This adds a tiny bit of logic to fix that. See below for the fix (note the lack of version selection prompt):
https://user-images.githubusercontent.com/8854718/202500267-3e31ef39-9db3-4234-aacd-0e17ff8deaf5.mp4
Do tests pass?
> fix: don't prompt for version if only one exists

- __tests__/cmds/open.test.ts
- package-lock.json
The `no-unreachable` ESLint rule gets disabled by the TS ESLint for some reason so I've re-enabled it and released a new version of our shared config.
> fix: unreachable code and those not getting flagged by eslint

- .eslintrc
- CONTRIBUTING.md
- README.md
- __tests__/helpers/get-api-mock.ts
- __tests__/lib/fetch.test.ts
- src/lib/fetch.ts
- src/lib/getPkgVersion.ts
| 🚥 Fix #680 |
| :-- |
Adds the ability to configure a proxy via the `HTTPS_PROXY` environmental variable. As part of this:
Do tests pass?
> feat: proxy support

- README.md
- __tests__/cmds/openapi/reduce.test.ts
- src/cmds/openapi/reduce.ts
| 🚥 Fix #683 |
| :-- |
Adds the ability to pass in opts to the `openapi:reduce` command.
Check out this branch and run the following commands:
```sh
npm ci
npm run debug -- openapi:reduce __tests__/__fixtures__/petstore-simple-weird-version.json --tag pet --out test.json
npm run debug -- openapi:reduce __tests__/__fixtures__/petstore-simple-weird-version.json --path /unknown-path --out test.json
```
Does it work?
> feat(`openapi:reduce`): pass opts

- README.md
Per an issue raised in #697, this more prominently discourages use of `rdme login` in automated environments.
> docs: better callout for `rdme login` usage

- jest.config.js
While upgrading `oas` to Jest 29 I also encountered the same issue we had here where `ts-jest` wasn't picking up our `tsconfig.json` file. Turns out that because we're setting up `transform` on `.ts` files ourselves we don't need this extra `presets` config as it's already being loaded from the `transform` config. Loading both of these was causing the first preset to get loaded without unit test `tsconfig`.
Kind of an annoying gotcha but all tests should still be passing with this change.
> test: cleaning up our jest config

- __tests__/cmds/docs/prune.test.ts
- src/lib/getDocs.ts
| 🚥 Fixes #710 |
Turns out our response payloads from [`GET /categories/{slug}/docs`](https://docs.readme.com/main/reference/getcategorydocs) looks like this for [pages that contain subpages](https://docs.readme.com/main/docs/navigating-your-hub):
```json
[
...
{
"title": "Navigating Your Hub",
"slug": "navigating-your-hub",
"order": 4,
"hidden": false,
"children": [
{
"title": "Search + Search API",
"slug": "search",
"order": 0,
"hidden": false
},
{
"title": "Quick Nav in the API Reference",
"slug": "quick-nav-api-reference",
"order": 1,
"hidden": false
}
]
}
]
```
This PR fixes our `docs:prune` command to account for child pages.
Do tests pass?
> fix(`docs:prune`): prune child docs

- README.md
- __tests__/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/convert.test.ts
- __tests__/lib/__snapshots__/commands.test.ts.snap
- package.json
- src/cmds/index.ts
- src/cmds/openapi/convert.ts
- src/cmds/openapi/index.ts
- src/cmds/openapi/inspect.ts
- src/cmds/openapi/reduce.ts
- src/lib/logger.ts
- src/lib/prepareOas.ts
This exposes our internal Swagger and Postman spec conversion work that we do into a new `openapi:convert` command as it may be be useful to have outside of the context of regular spec uploading and validation.
It works the same as our other `openapi:*` commands and prompts you for specs, accepts a working directory, and has an `--out` argument for storing the converted spec.
```
npx ts-node openapi:convert
```
> feat(openapi): exposing our spec conversion tooling to a new `:convert` command

- __tests__/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/index.test.ts
- __tests__/cmds/openapi/reduce.test.ts
- package-lock.json
- package.json
- src/cmds/openapi/convert.ts
- src/cmds/openapi/index.ts
- src/cmds/openapi/inspect.ts
- src/cmds/openapi/reduce.ts
- src/cmds/openapi/validate.ts
- src/lib/baseCommand.ts
- src/lib/prepareOas.ts
| 🚥 Fixes #716 |
This PR adds a new `--title` flag to both the `openapi` and `openapi:reduce` commands that overrides the `info.title` field in an API definition prior to syncing/reducing the output definition. The bulk of this change can be found in this commit: https://github.com/readmeio/rdme/pull/718/commits/8b088622338f683c0da4c6c8a4c279a03f3d455f
As part of this process, I made a few related cleanups/refactors:
You can test this out by running `openapi:reduce`:
```sh
npm run debug -- openapi:reduce __tests__/__fixtures__/petstore-simple-weird-version.json --title "some alternative title"
```
> feat(openapi): add ability to override title

- __tests__/lib/fetch.test.ts
- src/lib/fetch.ts
- src/lib/logger.ts
As we start surfacing [`Warning` headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Warning) from the ReadMe API, we can now surface them in our formatted warning output.
Don't have an example API request but do tests pass?
> feat(api): surface `Warning` response headers

- .github/workflows/docs.yml
GitHub Actions now supports variables, so swapping out the version secret for a version variable.
Further reading: https://github.blog/changelog/2023-01-10-github-actions-support-for-configuration-variables-in-workflows/
In the [docs syncing dry run step](https://github.com/readmeio/rdme/actions/runs/4008520309/jobs/6882778511#step:8:10), note how the version is no longer masked:
Here's what it looks like for [the same workflow in `main`](https://github.com/readmeio/rdme/actions/runs/3877892669/jobs/6613439893#step:8:10):
> ci: use var instead of secret

- src/cmds/categories/create.ts
- src/cmds/docs/edit.ts
- src/cmds/openapi/index.ts
- src/cmds/versions/create.ts
- src/cmds/versions/update.ts
- src/lib/fetch.ts
- src/lib/getCategories.ts
- src/lib/prompts.ts
- src/lib/streamSpecToRegistry.ts
- src/lib/syncDocsPath.ts
- src/lib/versionSelect.ts
When debugging the minor uptick in API errors we saw last week, I realized some of our API response logging in `rdme` was inconsistent or incomplete. We already have a solid helper for reading/logging/parsing API responses in `handleRes`, so I made some refactors so we can reuse it in as many places as possible.
Do tests still pass?
> fix: better logging of API responses

- __tests__/cmds/docs/prune.test.ts
- src/lib/deleteDoc.ts
- src/lib/getDocs.ts
Noticed two tiny issues in the `docs:prune` command that are fixed in this PR:
Do tests pass?
> fix: page deletion order in `docs:prune`

- __tests__/lib/fetch.test.ts
- package-lock.json
- package.json
- src/cmds/swagger.ts
- src/cmds/validate.ts
- src/cmds/versions/update.ts
- src/lib/configstore.ts
- src/lib/isCI.ts
Before:
```
Package                Current   Wanted   Latest  Location                            Depended by
@readme/eslint-config   10.3.2   10.5.0   10.5.0  node_modules/@readme/eslint-config  rdme
@types/jest             29.2.5   29.4.0   29.4.0  node_modules/@types/jest            rdme
@types/validator       13.7.10  13.7.11  13.7.11  node_modules/@types/validator       rdme
chalk                    4.1.2    4.1.2    5.2.0  node_modules/chalk                  rdme
config                   3.3.8    3.3.9    3.3.9  node_modules/config                 rdme
configstore              5.0.1    5.0.1    6.0.0  node_modules/configstore            rdme
eslint                  8.31.0   8.33.0   8.33.0  node_modules/eslint                 rdme
jest                    29.3.1   29.4.1   29.4.1 …
```
> chore(deps): bump

- __tests__/cmds/changelogs/index.test.ts
- __tests__/cmds/changelogs/single.test.ts
- __tests__/cmds/custompages/index.test.ts
- __tests__/cmds/custompages/single.test.ts
- __tests__/cmds/docs/index.test.ts
- __tests__/cmds/docs/single.test.ts
- src/lib/syncDocsPath.ts
| 🚥 Fixes #738 |
For some background, here's the general workflow for when syncing a Markdown file to ReadMe via the `rdme docs` (or `changelogs`/`custompages`) command:
1. Grab the slug from the page
2. Make [a `GET` request](https://docs.readme.com/main/reference/getdoc) to the ReadMe API to confirm that the page exists
3. If the page exists, update the page via [a `PUT` request](https://docs.readme.com/main/reference/updatedoc)
4. If the page does **not** exist, create the page via [a `POST` request](https://docs.readme.com/main/reference/createdoc)
The problem in step 3 is that we take the response body from the `GET` request (called `existingDoc` in the code below) and merge that with the Markdown file's data when making the `PUT` request: …
> fix(docs): don't merge payloads for PUT requests

- .github/workflows/ci.yml
- jest.config.js
| 🚥 Fixes #617 |
Code coverage in Github Actions is broken due to Jest, for whatever reason, not automatically creating code coverage directories. I was able to partialy fix this by first creating a `coverage/` directory but even after chmod'ing with 777 permissions it still wouldn't create `coverage/lconv-report/`.
As `coverage/lconv-report` has a whole bunch of subdirectories that I have no desire to try to keep up with in a CI workflow, I've just changed our Jest code coverage to use a simpler reporter that dumps to the console.
> ci: fix code coverage in github actions

- .eslintrc
- __tests__/cmds/docs/index.test.ts
- __tests__/cmds/docs/single.test.ts
- __tests__/cmds/openapi/index.test.ts
- __tests__/helpers/get-gha-setup.ts
- __tests__/helpers/setup-gha-env.ts
- __tests__/lib/fetch.test.ts
- src/cmds/openapi/index.ts
- src/lib/fetch.ts
- src/lib/isCI.ts
- src/lib/prepareOas.ts
- src/lib/syncDocsPath.ts
| 🚥 Fixes RM-6466 |
**tl;dr** we're adding two new request headers when hitting the ReadMe API! This will facilitate some upcoming changes (see RM-5907) 👀
Here are the two new request headers:
1. **`x-rdme-ci`**: if the command is being run in a CI environment, this will be set to the name of the CI environment as determined by [`ci-info`](https://github.com/watson/ci-info) (e.g., `GitHub Actions`[^1])
1. **`x-readme-source-url`**: if the command is syncing an OpenAPI or Markdown doc to ReadMe, this header[^3] contains the source URL for the file (if applicable). There are two ways that we determine the source file:
1. If the command is being run via GitHub Actions and a local file is being synced, we use a variety of [default environment …
> feat(GHA): add req header containing file URL

- __tests__/helpers/get-api-mock.ts
- __tests__/lib/fetch.test.ts
- src/cmds/categories/create.ts
- src/cmds/docs/edit.ts
- src/cmds/openapi/index.ts
- src/cmds/versions/create.ts
- src/cmds/versions/delete.ts
- src/cmds/versions/index.ts
- src/cmds/versions/update.ts
- src/lib/deleteDoc.ts
- src/lib/getCategories.ts
- src/lib/getDocs.ts
- src/lib/loginFlow.ts
- src/lib/prompts.ts
- src/lib/readmeAPIFetch.ts
- src/lib/streamSpecToRegistry.ts
- src/lib/syncDocsPath.ts
- src/lib/versionSelect.ts
Follow-up PR to #735 based on this feedback from @erunion: https://github.com/readmeio/rdme/pull/735#discussion_r1093558964
No functional changes, just a lot of refactors. If the build and tests pass, we should be good to go!
> refactor(fetch): `readmeAPIFetch`, consolidate base URL

- package-lock.json
| 🚥 Fixes RM-6112 |
Upgrades `oas-normalize` to move to our `postman-to-openapi` fork as we have some fixes for `undefined` response HTTP status codes that have been plaguing some users.
> fix: upgrading `oas-normalize` to move to our `postman-to-openapi` fork

- __tests__/helpers/github-workflow-schema.json
- package-lock.json
- package.json
| 🚥 Fixes https://github.com/readmeio/rdme/issues/778 |
Resolve a bug in our YAML parsing in [oas-normalize](https://npm.im/oas-normalize) where if you had an `info.version` string in an OpenAPI definition that looked like `2015-04-22T10:03:19.323-07:00` it would be improperly parsed out as a `Date` object -- causing any command that depends on that to fail as it expects to be working with a string.
> fix(openapi): yaml strings would be improperly parsed as Date objects

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .releaserc.yml
- Dockerfile
- action.yml
- bin/docker.js
- bin/set-action-image.js
- bin/set-version-output.js
- bin/verify-clis.sh
| 🚥 Fixes RM-6538 |
The moment we've been waiting for y'all: enhancing our `semantic-release` workflow to automatically publish docker images to the GitHub Container Registry!
There are a bunch of moving parts, but if you look at the Linear ticket, I've added comments with links to a couple internal videos that I created
I did a couple of test pushes to the Container Registry and confirmed that a working, containerized version of `rdme` is pushed to the registry!
- You can see the release workflow here: https://github.com/readmeio/rdme/actions/runs/4350052453/jobs/7600379201
- And the corresponding image in the container registry here: https://github.com/readmeio/rdme/pkgs/container/rdme/75372142
And the performance gains are pretty incredible. Here's [the …
> feat: container registry

- action.yml
- src/cli.ts
When digging into #778 I realized that it'd be useful for commands like `rdme versions` and `rdme openapi --raw` to be able to use those JSON output in subsequent GitHub workflow steps. This PR does the following:
- Makes a tiny change to our CLI wrapper file to set the command results [as output parameters](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter)
- Documents this new output in `action.yml` (which I don't even think is surfaced anywhere in the marketplace or anything)
Do tests still pass?
> feat: add GHA output with command result

- __tests__/cmds/docs/edit.test.ts
- __tests__/cmds/open.test.ts
- __tests__/cmds/openapi/index.test.ts
- __tests__/cmds/openapi/inspect.test.ts
- __tests__/index.test.ts
- __tests__/lib/commands.test.ts
- src/cmds/oas.ts
Writing some tests as part of #788 and ended up going down a bit of a rabbit hole 🕳️
Do tests still pass?
> chore: remove outdated `oas` language, testbed cleanup 🧹

- package-lock.json
This upgrades `oas` to incorporate the fix in https://github.com/readmeio/oas/pull/753, which fixes an issue with `openapi:reduce`. This also upgrades other outdated dependencies.
Before:
```
Package                          Current   Wanted   Latest  Location                                      Depended by
@commitlint/cli                   17.5.1   17.6.1   17.6.1  node_modules/@commitlint/cli                  rdme
@commitlint/config-conventional   17.4.4   17.6.1   17.6.1  node_modules/@commitlint/config-conventional  rdme
@types/jest                       29.5.0   29.5.1   29.5.1  node_modules/@types/jest                      rdme
@types/validator                 13.7.14  13.7.15  13.7.15  node_modules/@types/validator                 rdme
chalk                              4.1.2 …
```
> fix(deps): bump `oas` (and others)

- npm-shrinkwrap.json
- package.json
This fixes a quirk with Postman to OpenAPI conversions where if a Postman response was documented without a description it also wouldn't get one in the converted OpenAPI definition, resulting in a definition that does not validate.
See https://github.com/readmeio/postman-to-openapi/pull/3 for the fix.
> fix(openapi): postman responses without a response now get one

- __tests__/lib/fetch.test.ts
- src/lib/readmeAPIFetch.ts
| 🚥 Fixes #816 |
This reworks the fix I had in #817 to utilize [the `URL` constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) to construct the URL that we pass in the `x-readme-source-url` header. That way we can properly encode weird characters like in #817, in addition to also ensuring that the string itself is a valid URL.
Check out the new test case I added.
> fix(fetch): stricter source URL type-checking

- __tests__/cmds/openapi/inspect.test.ts
- __tests__/lib/createGHA.test.ts
- npm-shrinkwrap.json
- package.json
- src/cmds/categories/create.ts
- src/cmds/login.ts
- src/cmds/open.ts
- src/cmds/openapi/convert.ts
- src/cmds/openapi/index.ts
- src/cmds/openapi/inspect.ts
- src/cmds/openapi/reduce.ts
- src/lib/analyzeOas.ts
- src/lib/apiError.ts
- src/lib/baseCommand.ts
- src/lib/commands.ts
- src/lib/getDocs.ts
- src/lib/help.ts
- src/lib/readmeAPIFetch.ts
Our core ESLint standards now includes the [eslint-plugin-typescript-sort-keys](https://www.npmjs.com/package/eslint-plugin-typescript-sort-keys) plugin for enforcing consistent sorting of TS `interface` props.
> chore(eslint): consistenly sorting on interface props

- MAINTAINERS.md
- README.md
No material changes here, just a small syntax update to reflect the updated GFM callout format: https://github.com/orgs/community/discussions/16925
Per the author:
> A new syntax, `[!NOTE]`, has been added, which will gradually replace the old one. However, the old syntax will continue to work for some time.
> docs: use updated callout syntax

- __tests__/cmds/openapi/__snapshots__/inspect.test.ts.snap
- src/cmds/openapi/inspect.ts
Noticed a tiny formatting error when running `openapi:inspect` against an OpenAPI 3.0 definition:
I made the type a little stricter and tweaked the logic a bit so now it looks like this:
I don't love how the URL and this disclaimer text have the same formatting, but this is probably good enough for now.
Do tests pass and does this change look good?
> fix(openapi/inspect): small url formatting error

- __tests__/cmds/versions/create.test.ts
- __tests__/cmds/versions/update.test.ts
- __tests__/lib/prompts.test.ts
- src/cmds/versions/create.ts
- src/cmds/versions/update.ts
- src/lib/baseCommand.ts
- src/lib/castStringOptToBool.ts
- src/lib/prompts.ts
| 🚥 Resolves RM-7747 |
Per RM-7747, our `versions:create` and `versions:update` commands don't properly set boolean values correctly, for example:
```sh
rdme versions:update --beta=false 1.0.1
rdme versions:update --beta=yo 1.0.1
```
The code for prompting the user and constructing the request payloads is all very messy and hard to follow, so this PR utilizes the incredibly handy `prompts.override` method to vastly simplify things and improve readability in a few places, which in turn fixes a few weird bugs:
If tests pass then we should be good, but feel free to try a few flows with the `versions:create` and `versions:update` commands to see if everything works as expected.
> fix(versions): general refactors to handle flag edge cases

- src/cmds/openapi/convert.ts
- src/cmds/openapi/index.ts
- src/cmds/openapi/inspect.ts
- src/cmds/openapi/reduce.ts
- src/cmds/openapi/validate.ts
- src/lib/createGHA/index.ts
As part of the work I was doing in #858, this adds some helpful debugging for such situations.
> chore: add debug statements for `process.chdir`

- __tests__/cmds/versions/create.test.ts
- __tests__/cmds/versions/update.test.ts
- src/cmds/versions/create.ts
- src/cmds/versions/update.ts
- src/lib/prompts.ts
| 🚥 Resolves https://github.com/readmeio/rdme/issues/871 |
#861 introduced a regression where the CLI will always set `is_hidden: true` in the API payload if the `main` flag is set to `true`, which throws an error in our version model validation 😬 this PR fixes that.
Confirmed the fix locally and added tests with strict payload assertions to make sure everything checks out.
> fix(versions): fix ability to set main version

- .github/workflows/lint-pr-title.yml
Our release process relies on `semantic-release` and on our PR titles following conventional commit guidelines, so this PR adds a workflow to validate PR titles accordingly.
I also updated our repository settings so we now default to the PR title when merging PRs in (weird how that's not the default):
Per [their docs on the `pull_request_target` event](https://github.com/amannn/action-semantic-pull-request#event-triggers), this workflow won't run until it's merged into our default branch so there's no way to test it until then.
> ci: validate PR titles

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/simple.yml
- __tests__/cmds/docs/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/__snapshots__/validate.test.ts.snap
- __tests__/lib/__snapshots__/createGHA.test.ts.snap
- __tests__/single-threaded/lib/__snapshots__/createGHA.test.ts.snap
- __tests__/single-threaded/openapi/__snapshots__/index.test.ts.snap
- __tests__/single-threaded/openapi/__snapshots__/validate.test.ts.snap
- documentation/github-actions-docs-example.md
- documentation/github-actions-openapi-example.md
- documentation/legacy-github-action.md
- documentation/rdme.md
- src/lib/createGHA/baseFile.ts
Did a quick find-and-replace to update our GitHub workflow files and our GitHub Actions onboarding workflow generation to use [`actions/checkout@v4`](https://github.com/actions/checkout/releases/tag/v4.0.0)
If our tests pass, we should be good to go since we're actually using `actions/checkout@v4` against the real `rdme` GitHub Action.
> feat: use `actions/checkout@v4` everywhere

- bin/rdme.js
As I feared, the current version in `next` yields this whenever you run an `rdme` CLI command:
This was surprisingly not straightforward (it was _**buried**_ in the comments: https://github.com/nodejs/node/issues/10802#issuecomment-573376999) and I don't love this solution, but I confirmed that adding a `NODE_OPTIONS` env variable to the entry shebang should fix this.
I `npm link`'d locally and confirmed the warning goes away:
> fix: hide `ExperimentalWarning`

- README.md
- __tests__/cmds/versions/create.test.ts
- __tests__/cmds/versions/update.test.ts
- __tests__/lib/prompts.test.ts
- src/cmds/versions/create.ts
- src/cmds/versions/update.ts
- src/lib/baseCommand.ts
- src/lib/prompts.ts
This PR updates our `versions:create` and `versions:update` commands to bring parity with our CLI flags and [our API flags](https://docs.readme.com/main/reference/createversion). The only flag that needed to be updated was `isPublic`, which has been renamed to `hidden`. This PR is a breaking change since the flag needs to be renamed and flipped..
This PR also cleans up our copy related to these commands and cleans up a bunch of tests and comments.
Does the copy look good and do tests pass?
> feat(versions): flag parity with API, copy fixes

- tsconfig.json
Cleans up and modernizes our `tsconfig`!
If the build passes across the board we should be good to go.
> chore: tsconfig cleanup

- __tests__/__snapshots__/index.test.ts.snap
- __tests__/cmds/openapi/convert.test.ts
- __tests__/lib/__snapshots__/commands.test.ts.snap
- __tests__/single-threaded/openapi/convert.test.ts
- src/cmds/openapi/convert.ts
Tweaks the messaging and functionality in our `openapi:convert` command so it can support OpenAPI files. It's a bit of a niche use-case but it might be handy for seeing our bundled output.
Do tests pass and does the copy look good?
> feat(openapi/convert): support openapi in convert command

- README.md
- __tests__/index.test.ts
- src/lib/getCurrentConfig.ts
| 🚥 Resolves #948 |
Adds the ability to pass in the API key via the `README_API_KEY` environmental variable.
Do the docs + tests + etc. look good?
> feat: support `README_API_KEY` env var

- package-lock.json
Bumping deps again since MSW finally includes support for TypeScript 5.3.
**Before**
```
Package                          Current  Wanted  Latest  Location                                      Depended by
@commitlint/cli                   18.4.3  18.4.4  18.4.4  node_modules/@commitlint/cli                  rdme
@commitlint/config-conventional   18.4.3  18.4.4  18.4.4  node_modules/@commitlint/config-conventional  rdme
@vitest/coverage-v8                1.1.1   1.1.3   1.1.3  node_modules/@vitest/coverage-v8              rdme
@vitest/expect                     1.1.1   1.1.3   1.1.3  node_modules/@vitest/expect                   rdme
knip                              3.10.0  3.12.0  3.12.0  node_modules/knip                             rdme
msw                               2.0.11  2.0.12 …
```
> chore(deps): bump using `npm up`

- src/lib/prepareOas.ts
Noticed an un-handled spinner when running an `openapi:validate` command:
Do tests still pass?
> fix(openapi): add spinner catch statement

- __tests__/__fixtures__/docs/docs-with-parent-ids/child.md
- __tests__/__fixtures__/docs/docs-with-parent-ids/friend.md
- __tests__/__fixtures__/docs/docs-with-parent-ids/parent.md
- __tests__/__fixtures__/docs/docs-with-parent-ids/with-parent-doc.md
- __tests__/__fixtures__/docs/multiple-docs-cycle/child.md
- __tests__/__fixtures__/docs/multiple-docs-cycle/grandparent.md
- __tests__/__fixtures__/docs/multiple-docs-cycle/parent.md
- __tests__/__fixtures__/docs/multiple-docs-no-parents/child.md
- __tests__/__fixtures__/docs/multiple-docs-no-parents/friend.md
- __tests__/__fixtures__/docs/multiple-docs/child.md
- __tests__/__fixtures__/docs/multiple-docs/friend.md
- __tests__/__fixtures__/docs/multiple-docs/grandparent.md
- __tests__/__fixtures__/docs/multiple-docs/parent.md
- __tests__/cmds/docs/multiple.test.ts
- package-lock.json
- package.json
- src/lib/readDoc.ts
- src/lib/syncDocsPath.ts
| 🚥 Resolves RM-8336 |
| :------------------ |
When syncing docs, it sorts them by their parents!
Users reported issues where if a parent document was in a directory, it could error out because it would get synced after one of its children.
Not sure :grimacing:.
> feat: sort when syncing by parent

- __tests__/cmds/openapi/index.test.ts
- __tests__/index.test.ts
- __tests__/lib/analyzeOas.test.ts
- __tests__/lib/fetch.test.ts
- __tests__/lib/getPkgVersion.test.ts
- __tests__/single-threaded/lib/createGHA.test.ts
- bin/set-action-image.js
- bin/set-major-version-tag.js
- package.json
- src/cli.ts
- src/index.ts
- src/lib/config.ts
- src/lib/configstore.ts
- src/lib/getPkgVersion.ts
- src/lib/readmeAPIFetch.ts
TC39 updated their import _assertions_ to be import _attributes_ and it's a bit of a mess now that we're running tests against Node v22.
Here's what importing JSON in ESM used to look like:
```js
import { x } from "./mod" assert { type: "json" }
```
now it looks like this:
```js
import { x } from "./mod" with { type: "json" };
```
Support for this new `with` keyword was added in [Node v18.20.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#added-support-for-import-attributes) and [Node v20.10.0](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-11-22-version-20100-iron-lts-targos) (and is supported on all v21 and v22 channels), but importantly the older `assert` keyword is **_not_** supported in Node v22, so unfortunately our …
> fix: use newest import attributes syntax

- __tests__/helpers/github-workflow-schema.json
- package-lock.json
| [![PR App][icn]][pr] | 🚥 Resolves RM-9343 |
| :------------------: | :------------------: |
This bumps `@readme/openapi-parser` to include these changes:
- https://github.com/readmeio/openapi-parser/pull/259
- https://github.com/readmeio/openapi-parser/pull/264
These fix an issue where the existence of the `description` property under `server.variables` would fail validation. 
Customers should be able to upload valid OAS 3.1 files again without error'ing.
The following OAS file should not hit any validation errors:
<details>
<summary>OAS 3.1 file</summary>
```json
{
"openapi": "3.1.0",
"info": {
"version": "1.0",
"title": "Invalid API"
},
"servers": [
{
"url": "https://{subdomain}.io",
"variables": {
"subdomain": {
"default": "petstore",
"description": "Subdomain description"
}
}
}
], …
```
> chore(deps): update @readme/openapi-parser

- src/commands/openapi/convert.ts
- src/commands/openapi/inspect.ts
I accidentally added the `titleFlag` (allows you to overwrite the `info.title` field) to `openapi:inspect` in #1068 which doesn't make a ton of sense so I'm removing it in this PR. In doing this, I also decided to add the `title` flag to `openapi:convert` b/c why not.
> feat: add `title` flag to `openapi:convert`

- __tests__/commands/openapi/validate.test.ts
- documentation/commands.md
- documentation/rdme.md
- src/commands/open.ts
- src/commands/openapi/validate.ts
- src/lib/config.ts
(writing these below as such so they get picked up by `semantic-release`)
BREAKING CHANGE: `rdme validate` has been removed, use `rdme openapi:validate` instead.
BREAKING CHANGE: `rdme open` is now deprecated
also updates our docs accordingly
> feat!: remove `validate`, deprecate/hide `open`

- package.json
Noticed a tiny issue where the `documentation/commands.md` file is displaying an outdated version. I'm not entirely tracking why (esp b/c the `oclif.manifest.json` file seems to have the correct version in the npm release?) but I believe that using the `version` npm lifecycle script will ensure that the file is bumped with the `npm` version that's being bumped **_to_**, rather than the one **_prior_** to bumping.
Further reading:
- https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package.jsons-version
- https://github.com/semantic-release/npm
- https://github.com/semantic-release/git
- https://docs.npmjs.com/cli/v10/commands/npm-version
we'll have to just release this and see 🤷🏽
> fix(npm): tweak npm lifecycle scripts

- __tests__/lib/fetch.test.ts
- src/commands/categories/create.ts
- src/commands/openapi/index.ts
- src/commands/versions/create.ts
- src/commands/versions/delete.ts
- src/commands/versions/index.ts
- src/commands/versions/update.ts
- src/lib/deleteDoc.ts
- src/lib/getCategories.ts
- src/lib/getDocs.ts
- src/lib/loginFlow.ts
- src/lib/prompts.ts
- src/lib/readmeAPIFetch.ts
- src/lib/streamSpecToRegistry.ts
- src/lib/syncDocsPath.ts
- src/lib/versionSelect.ts
Describe in detail what this PR is for.
> refactor: rename a few more fetch functions

- src/lib/baseCommand.ts
`@oclif/core@4`[^1] updated their debug logs so the top-level scope of all logs is `oclif`. this means our debug logs look like this:
thanks, i hate it. this fixes them up so they look like this again:
[^1]: See the "Customizable Logger" section of [their release notes](https://github.com/oclif/core/releases/tag/4.0.0).
> fix: debug properly

- CONTRIBUTING.md
- MAINTAINERS.md
a few contributing doc cleanups, some of which i forgot to include in https://github.com/readmeio/rdme/pull/1081.
> docs: fix contributing docs up a bit

- .github/workflows/ci.yml
Adding a test so we can easily see errors when they're thrown in GitHub Actions. Also added a few related assertion steps.
Does the validation error show up properly? And do tests pass?
> ci: add test for validation failures

- __tests__/commands/openapi/refs.test.ts
- documentation/commands/openapi.md
- src/commands/openapi/refs.ts
Touched up a few things in https://github.com/readmeio/rdme/pull/1063!
Are my changes sound?
> fix: `openapi:refs` touch ups

- documentation/commands/categories.md
- documentation/commands/docs.md
- documentation/commands/openapi.md
- src/commands/openapi/index.ts
- src/lib/flags.ts
i realized that the `summary` and `description` fields are shown right next to each other so we can remove some of the duplication.
> docs: remove a few redundant flag descriptions

- __tests__/commands/categories/create.test.ts
- __tests__/commands/categories/index.test.ts
- __tests__/commands/changelogs/index.test.ts
- __tests__/commands/changelogs/single.test.ts
- __tests__/commands/custompages/index.test.ts
- __tests__/commands/custompages/single.test.ts
- __tests__/commands/docs/index.test.ts
- __tests__/commands/docs/multiple.test.ts
- __tests__/commands/docs/prune.test.ts
- __tests__/commands/docs/single.test.ts
- __tests__/commands/login.test.ts
- __tests__/commands/open.test.ts
- __tests__/commands/openapi/index.test.ts
- __tests__/commands/versions/create.test.ts
- __tests__/commands/versions/delete.test.ts
- __tests__/commands/versions/index.test.ts
- __tests__/commands/versions/update.test.ts
- __tests__/helpers/get-api-mock.ts
- __tests__/lib/fetch.test.ts
> chore: fix capitalization of APIv1

- bin/dev.js
- bin/run.js
Linux requires the `-S` flag when passing options to `node` command-line in executable files. This was fun to troubleshoot 🥴
Can Linux users run the CLI again? 😮‍💨
> fix: executable issue for linux users

- src/commands/docs/prune.ts
autocompletions were broken, seemingly due to the `guides prune` alias:
thankfully the fix is harmless and shouldn't result in any actual end user changes.
> fix(autocomplete): bad alias

- .github/workflows/release.yml
- __tests__/commands/logout.test.ts
- __tests__/commands/open.test.ts
- __tests__/commands/whoami.test.ts
- __tests__/helpers/get-gha-setup.ts
- __tests__/lib/createGHA.test.ts
- __tests__/lib/getPkgVersion.test.ts
- bin/dev.js
- bin/run.js
- bin/set-version-output.js
- src/lib/configstore.ts
- src/lib/createGHA/index.ts
- src/lib/getPkgVersion.ts
- src/lib/readmeAPIFetch.ts
Reverts readmeio/rdme#1117 since it's evidently breaking GitHub Actions workflows 🤡
> fix: revert #1117

- .github/workflows/ci.yml
- .github/workflows/release.yml
- __tests__/commands/logout.test.ts
- __tests__/commands/open.test.ts
- __tests__/commands/whoami.test.ts
- __tests__/helpers/get-gha-setup.ts
- __tests__/lib/createGHA.test.ts
- __tests__/lib/getPkgVersion.test.ts
- bin/dev.js
- bin/run.js
- bin/set-version-output.js
- package.json
- src/lib/configstore.ts
- src/lib/createGHA/index.ts
- src/lib/getPkg.ts
- src/lib/readmeAPIFetch.ts
we hit a bit of a wild edge case where the github action was only breaking in production builds due to how oclif loads the `package.json` and the only way we caught it was with [this failure](https://github.com/readmeio/rdme/actions/runs/12267183540/job/34226921877).
this PR reverts https://github.com/readmeio/rdme/pull/1119 (which in turn brings back https://github.com/readmeio/rdme/pull/1117) with a slight tweak in https://github.com/readmeio/rdme/pull/1120/commits/f9461b430e2318c00731c4f75d1506cd593d4970 to do the following:
- make our import paths friendlier to github actions
- manually copy over the `package.json` to our `dist/` directory whenever we run `npm run build`. TS was automatically handling this when we were using JSON imports before but now it's not able to pick up on the …
> fix: bring back #1117 without breaking everything

- README.md
- documentation/migration-guide.md
doc updates that we should push to the `v9` channel right before we release `v10`! see https://github.com/readmeio/rdme/pull/1113 for the sequencing of all of this.
> docs: v9 doc touch-ups

- CONTRIBUTING.md
- MAINTAINERS.md
updating our contrib docs to reflect our new release process and guidance for writing commands in an `oclif`-friendly way.
> docs: contrib docs refresh

- src/commands/openapi/upload.ts
- src/index.ts
- src/lib/prepareOas.ts
when reviewing https://github.com/readmeio/rdme/pull/1126, i noticed a few small bugs in our `prepareOas` helper function. this PR makes a few typesafety improvements so we shouldn't run into this issue again(?)
~~one outstanding question that i'd like to figure out prior to merge, see https://github.com/readmeio/rdme/issues/1142~~ (**edit**: going to continue bundling and handle this issue in a follow-up PR)
do tests + types pass?
> fix(openapi): type fixes in `prepareOas`

- .releaserc.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
takes the following changes from `v9` and reapplies them into `next` so the branches are in sync:
very curious if there's a better way to do this lol
do tests pass?
> chore: backport v9 changes back to v10

- package-lock.json
- package.json
- src/lib/readdirRecursive.ts
bumps `vitest` to 3.0, and also upgrades a bunch of other outdated deps.
**before:**
```
Package                                        Current          Wanted   Latest  Location                                             Depended by
@oclif/core                                      4.2.1           4.2.3    4.2.3  node_modules/@oclif/core                             rdme
@oclif/plugin-autocomplete                      3.2.16          3.2.17   3.2.17  node_modules/@oclif/plugin-autocomplete              rdme
@oclif/plugin-help                              6.2.20          6.2.21   6.2.21  node_modules/@oclif/plugin-help                      rdme
@oclif/plugin-not-found                         3.2.33          3.2.35   3.2.35  node_modules/@oclif/plugin-not-found                 rdme …
```
> chore(deps-dev): bump vitest to 3.0, `npm up`

- src/commands/changelogs.ts
- src/lib/baseCommand.ts
- src/lib/readmeAPIFetch.ts
- src/lib/syncDocsPath.legacy.ts
does the build + tests still pass?
> chore: smol refactors

- __tests__/commands/openapi/reduce.test.ts
- __tests__/commands/openapi/validate.test.ts
- __tests__/lib/createGHA.test.ts
- __tests__/lib/fetch.test.ts
- __tests__/lib/getPkgVersion.test.ts
This is just a **very** small typing improvement on some of our `console.*` unit test spies.
> chore: minor typing improvement on unit test spies

- __tests__/commands/changelogs/index.test.ts
- __tests__/commands/changelogs/single.test.ts
- __tests__/commands/login.test.ts
- __tests__/commands/openapi/convert.test.ts
- __tests__/commands/openapi/reduce.test.ts
- __tests__/commands/openapi/upload.test.ts
- __tests__/helpers/get-gha-setup.ts
- __tests__/helpers/global-setup.ts
- __tests__/lib/fetch.test.ts
- __tests__/lib/getPkgVersion.test.ts
- documentation/commands/changelogs.md
- documentation/rdme.md
- package-lock.json
- src/commands/changelogs.ts
- src/lib/baseCommand.ts
- src/lib/readDoc.ts
- src/lib/syncDocsPath.legacy.ts
- vitest.config.ts
chunks out a lot of PR feedback and random changes from #1159:
before:
```Package                    Current   Wanted   Latest  Location                                Depended by
@readme/better-ajv-errors    2.0.0    2.1.2    2.1.2  node_modules/@readme/better-ajv-errors  rdme
eslint                      8.57.1   8.57.1   9.19.0  node_modules/eslint                     rdme
oclif                      4.17.20  4.17.21  4.17.21  node_modules/oclif                      rdme
semver                       7.6.3    7.7.0    7.7.0  node_modules/semver                     rdme
undici                      5.28.5   5.28.5    7.3.0  node_modules/undici                     rdme
```
after:
```
Package  Current  Wanted  Latest  Location             Depended by
eslint    8.57.1  8.57.1  9.19.0 …
```
> chore: another grab bag of changes from #1159

- __tests__/commands/docs/prune.test.ts
- __tests__/commands/openapi/index.test.ts
- package-lock.json
- package.json
- src/lib/readdirRecursive.ts
before:
```
Package                                        Current   Wanted   Latest  Location                                             Depended by
@commitlint/cli                                 19.6.1   19.7.1   19.7.1  node_modules/@commitlint/cli                         rdme
@commitlint/config-conventional                 19.6.0   19.7.1   19.7.1  node_modules/@commitlint/config-conventional         rdme
@oclif/core                                      4.2.1    4.2.6    4.2.6  node_modules/@oclif/core                             rdme
@oclif/plugin-autocomplete                      3.2.16   3.2.20   3.2.20  node_modules/@oclif/plugin-autocomplete              rdme
@oclif/plugin-help                              6.2.20   6.2.24   6.2.24  node_modules/@oclif/plugin-help …
```
> chore(deps/v9): bump

- .vscode/settings.json
when pairing with @emilyskuo we noticed a handful of directories/files that i had configured myself but didn't configure for the repo writ large. figured all vscode users could benefit from this config.
do the search results properly exclude certain directories/files?
> chore(vscode): configure search exclusions

- bin/dev.js
- bin/run.js
fixes an issue where users of the `v9` channel are being told to upgrade to `v10` even though we're still maintaining the `v9` channel.
before:
after:
> fix(v9): point to correct dist-tag for outdated version notifications

- __tests__/commands/openapi/__snapshots__/upload.test.ts.snap
- __tests__/commands/openapi/upload.test.ts
- src/commands/openapi/upload.ts
| 🚥 Resolves RM-11894 |
Adding in a warning to alert users that the slug for the spec they're uploading will be updated
Updated the tests to use snapshots instead of match `result.stdout` or `result.error` to be more comprehensive.
> chore: add warning to rdme openapi upload for unexpected slugs

- __tests__/.eslintrc
- __tests__/bin.test.ts
- __tests__/commands/docs/upload.test.ts
- __tests__/commands/login.test.ts
- __tests__/commands/openapi/inspect.test.ts
- __tests__/commands/openapi/reduce.test.ts
- __tests__/commands/openapi/upload.test.ts
- __tests__/commands/openapi/validate.test.ts
- __tests__/lib/createGHA.test.ts
- __tests__/lib/fetch.test.ts
- __tests__/lib/getPkgVersion.test.ts
- __tests__/lib/validatePromptInput.test.ts
- package-lock.json
- package.json
The owner of `eslint-plugin-vitest` lost their NPM access to it was moved into `@vitest/eslint-plugin` a little over a year ago. This upgrades our `@readme/eslint-config` package to pull that in.
> chore(deps-dev): upgrading our eslint standards

- __tests__/commands/openapi/upload.test.ts
- documentation/legacy/rdme.md
- src/commands/openapi/upload.ts
| 🚥 Resolves https://github.com/readmeio/rdme/issues/1167 |
If an automated system runs `openapi upload` on a pre-existing file, then an overwrite prompt is shown. There is no way to skip this prompt which can lock up automated systems.
This PR adds a flag to skip the prompt.
**Case 1 - confirm existing behavior**
- Upload a new API spec to readme using `openapi upload {spec} --key={key} --slug={slug}`
- Try uploading the API spec again to trigger the overwrite prompt
**Case 2 - test new behavior**
- Upload a new API spec to readme using `openapi upload {spec} --key={key} --slug={slug}`
- Try uploading the API spec again using `openapi upload {spec} --key={key} --slug={slug} --overwrite` to …
> feat(openapi/upload): add `--confirm-overwrite` flag

- .gitignore
- CONTRIBUTING.md
- bin/dev.cmd
- package.json
- src/lib/configstore.ts
- src/lib/getPkg.ts
- vitest.config.ts
[node v20.18.3](https://nodejs.org/en/blog/release/v20.18.3) officially marked import attributes [as stable](https://nodejs.org/docs/latest-v20.x/api/esm.html#import-attributes). we have a lot of weird workarounds with our `oclif` setup in this repo in an effort to avoid import attributes and the ugly `ExperimentalWarning` outputs we see, but i don't think those should be a concern anymore, for a few reasons:
- our minimum required node.js version is node 20, so it should be a non-disruptive change for users to upgrade to the latest node 20 channel
- even if folks are on <20.18.2, the `ExperimentalWarning` outputs log to `stderr` so it shouldn't affect any command output-based workflows, which almost always are relying on `stdout`. plus, we discourage this kind of scripting and recommend …
> refactor: bring back json imports

- __tests__/commands/openapi/__snapshots__/validate.test.ts.snap
- __tests__/commands/openapi/validate.test.ts
rewrites our tests for `openapi validate` to be more compliant with [our contributing guidelines](https://github.com/readmeio/rdme/blob/next/CONTRIBUTING.md#code-style-guidelines). i initially wrote them this way to minimize the amount of legwork to get `oclif` working but this approach to testing is far more comprehensive and it should be much easier to drop in stray console logs for debugging purposes.
do tests still pass?
> test(openapi/validate): rewrite tests to be more comprehensive

- __tests__/helpers/get-api-mock.ts
- src/lib/readmeAPIFetch.ts
- src/lib/syncPagePath.ts
- src/lib/types.ts
- src/lib/types/index.ts
- src/lib/types/openapiDoc.ts
this PR updates our APIv2 openapi description as part of @emilyskuo's work in #1175 and chunks out the OAS into its own dedicated file since it's absolutely massive. you can check out the diff of the file changes [here](https://github.com/readmeio/rdme/compare/next...1346b8b78e5ff852a930ded5f3dc49f722f9cb03).
i tried messing around with JSON module imports so we can eventually automate these updates more easily, but we lose out on a lot of good strict typing that we currently have with `as const satisfies OASDocument`. annoying!
no functional changes. do tests still pass?
> chore: update local openapi snapshot

- package-lock.json
- tsconfig.json
a few small cleanups to our tsconfig + dep updates.
**before**
```
Package                                 Current   Wanted   Latest  Location                                             Depended by
@commitlint/cli                          19.7.1   19.8.0   19.8.0  node_modules/@commitlint/cli                         rdme
@commitlint/config-conventional          19.7.1   19.8.0   19.8.0  node_modules/@commitlint/config-conventional         rdme
@oclif/core                               4.2.8   4.2.10   4.2.10  node_modules/@oclif/core                             rdme
@oclif/plugin-autocomplete               3.2.24   3.2.26   3.2.26  node_modules/@oclif/plugin-autocomplete              rdme
@oclif/plugin-help                       6.2.26   6.2.27   6.2.27  node_modules/@oclif/plugin-help …
```
> chore: bump deps, tsconfig tweaks

- src/lib/types/openapiDoc.ts
refreshes our openapi doc for changes i have in store in RM-12356. grabbed from [here](https://docs.readme.com/main/openapi/readme-api-v2-beta.json).
do tests still pass?
> chore: refresh openapi definition

- knip.ts
- package.json
- src/lib/readmeAPIFetch.ts
- src/utils.ts
exposes a handful of utils in a new `rdme/utils` export. figured this would be a good spot to add more as we think of them.
do tests pass?
> feat: expose fetch utils

- __tests__/commands/docs/__snapshots__/upload.test.ts.snap
- __tests__/commands/docs/upload.test.ts
- src/lib/readmeAPIFetch.ts
- src/lib/syncPagePath.ts
| 🚥 Resolves RM-11904 |
when making `HEAD` requests, there is no response body, meaning that errors are totally unhelpful. this switches our initial page fetch requests to use the `GET` method.
> fix(docs/upload): switch from `HEAD` to `GET` for initial page fetch

- src/lib/types/index.ts
- src/types.ts
Exposes a new `APIKeyRepresentation` type for use in plugins.
> feat: exposing types for creating API keys to plugins

- package-lock.json
- package.json
- src/commands/docs/migrate.ts
- src/lib/baseCommand.ts
- src/lib/hooks/exported.ts
- src/lib/readPage.ts
- src/lib/readmeAPIFetch.ts
- src/lib/types/index.ts
- src/lib/unzip.ts
- src/types.ts
| 🚥 Resolves RM-12508 |
this isn't a ton of logic but it could definitely use a test or two. will do a more comprehensive pass of tests in follow-up PRs later this week.
> feat(docs/migrate): add ability to unzip archives

- src/lib/readmeAPIFetch.ts
- src/lib/syncPagePath.ts
We've been running into issues with `doc:upload` calls processing 6 pages and then failing out with undici timeout errors despite no actual request ever happening. I don't really know what's going on with the `allSettled` or undici and why it's consistently failing but reworking `doc:upload` to process each page in the batch one by one resolves our issues (albeit at the expensive of making the command slower).
> fix: timeouts on `doc:upload`

- __tests__/commands/docs/__snapshots__/migrate.test.ts.snap
- __tests__/commands/docs/__snapshots__/upload.test.ts.snap
- __tests__/commands/docs/migrate.test.ts
- __tests__/commands/docs/upload.test.ts
- src/commands/docs/migrate.ts
- src/commands/docs/upload.ts
noticed the outputs of our demo include a warning output. exposes a little flag for us to hide that warning.
see tests
> feat(docs): add `--hide-experimental-warning` flag

- __tests__/commands/docs/__snapshots__/upload.test.ts.snap
- __tests__/commands/docs/upload.test.ts
- src/commands/docs/migrate.ts
- src/commands/docs/upload.ts
- src/index.ts
- src/lib/hooks/exported.ts
- src/lib/syncPagePath.ts
- src/types.ts
| 🚥 Resolves RM-12506 |
adds migration stats reporting to the `docs:migrate` command. this was a big exercise in strong types to ensure that plugin authors have enough guardrails when writing these stats for themselves.
as part of this:
do tests + types pass?
> feat(docs/migrate): migration stats

- __tests__/lib/frontmatter.test.ts
- src/commands/docs/migrate.ts
- src/lib/frontmatter.ts
- src/lib/syncPagePath.ts
- src/lib/validateFrontmatter.ts
i'm about to open up another PR for RM-12535 that adds a new `-confirm-autofixes` flag, and as part of that i got fed up and totally DRY'd up our duplicated validation logic so it's now basically the same between `docs:upload` and `docs:migrate`.
i also added a tiny enhancement to our frontmatter autofixing logic that allows the `hidden` attribute to accept flags like `'true'` and `'false'`.
`docs:migrate` is still in dire need of more test coverage so i've been testing it locally and confirmed that it's still working as expected. `docs:upload` has great test coverage so if those tests pass we should be in good shape.
> refactor: consolidate doc frontmatter validation logic

- package-lock.json
- src/commands/docs/migrate.ts
- src/lib/readdirRecursive.ts
- src/lib/types/openapiDoc.ts
**before**
```
Package                     Current   Wanted   Latest  Location                                 Depended by
@oclif/plugin-autocomplete   3.2.26   3.2.27   3.2.27  node_modules/@oclif/plugin-autocomplete  rdme
@types/validator            13.12.3  13.15.0  13.15.0  node_modules/@types/validator            rdme
@vitest/coverage-v8           3.1.1    3.1.2    3.1.2  node_modules/@vitest/coverage-v8         rdme
@vitest/expect                3.1.1    3.1.2    3.1.2  node_modules/@vitest/expect              rdme
eslint                       8.57.1   8.57.1   9.25.1  node_modules/eslint                      rdme
ignore                        7.0.3    7.0.4    7.0.4  node_modules/ignore                      rdme
knip                         5.46.4   5.50.5   5.50.5 …
```
> chore: bump oclif deps/types + openapi

- documentation/commands/changelogs.md
- documentation/commands/login.md
- documentation/commands/plugins.md
- src/commands/changelogs.ts
- src/commands/login.ts
- src/lib/help.ts
reworks how the help screens + docs sort our flags so we can define the order. noticed this in https://github.com/readmeio/rdme/pull/1238 now that we're using `--branch` instead of `--version`.
as a general nit, i prefer the `--key` flag is always first, and then the `--branch` (f.k.a. `--version`) flag is always second.
> docs: improved flag sorting

- __tests__/__fixtures__/docs/existing-docs/subdir/another-doc.md
- __tests__/commands/docs/__snapshots__/upload.test.ts.snap
- __tests__/commands/docs/upload.test.ts
- __tests__/commands/openapi/__snapshots__/upload.test.ts.snap
- __tests__/commands/openapi/upload.test.ts
- __tests__/lib/frontmatter.test.ts
- documentation/commands/docs.md
- documentation/commands/openapi.md
- src/commands/docs/upload.ts
- src/commands/openapi/upload.ts
- src/index.ts
- src/lib/flags.ts
- src/lib/help.ts
- src/lib/readmeAPIFetch.ts
- src/lib/syncPagePath.ts
- src/lib/types/index.ts
- src/lib/types/openapiDoc.ts
`rdme` users are now seeing these deprecation warnings to do some underlying ReadMe APIv2 changes:
```
⚠️  ReadMe API Warning: Our `/versions` endpoint URI family has been renamed to `/branches` and will be removed in the future.
```
with the changes in this PR, the documented flag to use for the `openapi upload` and `docs upload` command is `--branch`. the `--version` flag will continue to work, but users will now see this warning[^1]:
```
›   Warning: The "--version" flag has been deprecated. Use "--branch" instead.
```
added a bunch of test coverage to account for this and also updated our docs throughout. please flag any discrepancies you see!
[^1]: i know, it's on my list to consolidate our warning formatting 🫠
> fix: remove `/version` API deprecation warnings

- documentation/legacy/github-actions-docs-example.mdx
- documentation/legacy/github-actions-openapi-example.mdx
- documentation/legacy/legacy-github-action.mdx
- documentation/legacy/rdme.mdx
MDX syntax doesn't support HTML comments (and wow prettier does not play nicely with MDX) 😮‍💨 this converts our synced markdown pages over to MDX
> docs: convert legacy docs to MDX syntax

- .github/CODEOWNERS
- .github/dependabot.yml
GitHub is sunsetting `reviewers` support in Dependabot in favor of relying on existing CODEOWNERS functionality. 
https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
> chore: replacing `reviewers` in dependabot with a CODEOWNERS

- src/commands/openapi/inspect.ts
This change introduces an explicit whitelist of keys that `rdme inspect` will process from the data returned by `oas/analyzer`. By filtering on known keys, we ensure that any new fields added by the analyzer won’t be rendered until we’ve explicitly implemented their handling in `rdme`.
> feat: filter `oas/analyzer` data by allowed keys

- src/lib/syncPagePath.ts
- src/lib/types/index.ts
just a small type addition to reflect the new support for reference pages. we'll want to make a similar change for custom pages + changelog too.
> refactor: smol type improvement for reference pages

- documentation/migration-guide.md
clearer introduction for our rdme migration docs
Describe in detail what this PR is for.
> docs: migration intro edit

- knip.ts
[knip](https://knip.dev/) (a super powerful tool that we use in our lint step for catching dead code) pointed out a few bits of superfluous config (since these file are already defined [as entry points in the `package.json` file's `exports` property](https://github.com/readmeio/rdme/blob/013a2ea66c638f044720b1b975597d3c65e49390/package.json#L35-L39):
this PR cleans that up a bit!
the knip warnings are now gone:
> chore: knip config cleanup

- documentation/commands/changelog.md
- documentation/commands/custompages.md
- documentation/commands/docs.md
- documentation/commands/reference.md
- src/commands/changelog/upload.ts
- src/commands/custompages/upload.ts
- src/commands/docs/migrate.ts
- src/commands/docs/upload.ts
- src/commands/reference/upload.ts
- src/lib/flags.ts
- src/lib/pageCommandProperties.ts
- src/lib/syncPagePath.ts
this PR creates the initial documentation for all of the page upload commands. the documentation follows the format of [the `docs upload` documentation](https://github.com/readmeio/rdme/blob/next/documentation/commands/docs.md#rdme-docs-upload-path).
as part of this, i created a helper file to consolidate all of the command properties for these four commands, which should help with future command + documentation updates.
do the docs look good? and do all tests still pass?
> docs: initial docs for all page upload commands, property DRY

- __tests__/commands/changelog/__snapshots__/upload.test.ts.snap
- __tests__/commands/changelog/upload.test.ts
- __tests__/commands/custompages/__snapshots__/upload.test.ts.snap
- __tests__/commands/custompages/upload.test.ts
- __tests__/commands/pages/__snapshots__/upload.test.ts.snap
- __tests__/commands/pages/upload.test.ts
- src/commands/docs/migrate.ts
- src/lib/syncPagePath.ts
- src/lib/types/index.ts
- src/lib/validateFrontmatter.ts
| 🚥 Resolves RM-12355 |
with the way our `docs upload` / `reference upload` / etc. commands are set up, this is how a command workflow might go with what’s in `next`:
1. user runs command
2. `rdme` detects autofixable frontmatter, prompts user to fix it
3. user says yes
4. frontmatter is autofixed
5. pages are then uploaded to ReadMe
based on internal feedback, that flow contains too _**little**_ friction (e.g., the idea of doing steps 4 and 5 above in one fell swoop is a little heavy-handed and is throwing folks off).
this PR tweaks this a bit so this is the new flow:
1. user runs command
2. `rdme` detects autofixable frontmatter, prompts user to fix it
3. user says yes
4. frontmatter is autofixed
5. `rdme` displays frontmatter autofixing results, prompts user to …
> fix(pages/upload): decouple autofixing and uploads

- __tests__/commands/changelog/__snapshots__/upload.test.ts.snap
- __tests__/commands/changelog/upload.test.ts
- __tests__/commands/custompages/__snapshots__/upload.test.ts.snap
- __tests__/commands/custompages/upload.test.ts
- __tests__/commands/pages/__snapshots__/upload.test.ts.snap
- __tests__/commands/pages/upload.test.ts
- src/lib/syncPagePath.ts
| 🚥 Resolves RM-13222 |
We had added in a check for projects with bidi connections, and required them to use the `--skip-validation` flag if it was enabled in order to use rdme to upload pages. This was maybe a bit overly prescriptive and we would actually want that validation to happen, even if bidi is enabled. We haven't fully ironed out what the behavior should be for customers using both rdme and bidi to sync docs, but for now, we're gonna remove all guardrails and checks. Once customers start really using these flows, we can see if we need to make updates.
Updated tests & they're still passing
> chore: remove bidi checks for page uploads

- .github/workflows/docs.yml
- __tests__/commands/changelog/__snapshots__/upload.test.ts.snap
- __tests__/commands/custompages/__snapshots__/upload.test.ts.snap
- __tests__/commands/openapi/__snapshots__/convert.test.ts.snap
- __tests__/commands/openapi/__snapshots__/upload.test.ts.snap
- __tests__/commands/pages/__snapshots__/upload.test.ts.snap
- src/commands/openapi/convert.ts
- src/lib/baseCommand.ts
- src/lib/logger.ts
- src/lib/readmeAPIFetch.ts
| 🚥 Resolves RM-13246 |
updates the formatting for our `this.warn()` statements so they're surfaced properly in github actions annotations.
i confirmed that these are showing up properly: https://github.com/readmeio/rdme/actions/runs/16131074838/job/45518517159
> feat(logger): improved warnings for GHA users

- __tests__/lib/getPkgVersion.test.ts
- src/lib/getPkg.ts
i noticed that our docs are displaying an improper node.js version range on the docker image examples — i fixed it up here: https://github.com/readmeio/docs-developers/compare/5b0fe7c01d74d5732070cd731eb42b6b92bcb17d...8f77f008b62555178ab1f405429dddb88ee69dd4
this PR ensures this remains correct.
> docs: use major node version in placeholders

- bin/dev.js
- bin/json-schema-store.js
- bin/run.js
- bin/set-major-version-tag.js
- bin/set-version-output.js
- biome.jsonc
- package-lock.json
- package.json
This incorporates our new [@readme/standards](http://npm.im/@readme/standards) package for colocating our Prettier and Biome configs. Prettier was previously a part of `@readme/eslint-config` but as we're slowly beginning to move away from ESLint it makes sense to have this Prettier config decoupled from ESlint.
> chore(biome): incorporating our new common biome config

- bin/set-version-output.js
- biome.jsonc
- package-lock.json
Upgrade Biome to the [latest release](https://github.com/biomejs/biome/releases/tag/%40biomejs/biome%402.1.2), which actually fixes a problem we were having with `.d.ts` files being picked up as `.js`!
> chore(deps-dev): upgrading biome

- package-lock.json
- package.json
- src/commands/openapi/inspect.ts
- src/commands/openapi/resolve.ts
Upgrades Biome and our `@readme/standards` package in order to flip on following rules:
* Our preference continues to be that types be written as interfaces.
All of these rules were/are a part of our ESLint config and just hadn't been ported into our Biome standards yet.
> chore(deps-dev): upgrading biome and our standards package

- bin/run.js
| 🚥 Resolves https://github.com/readmeio/rdme/issues/1331 |
as first discovered in https://github.com/readmeio/rdme/issues/1331, [`@oclif/core` uses **_its own_** node engine requirements and emits a warning](https://github.com/oclif/core/blob/70d3f192862a5adb548cbda68c6ee1ca8f724110/src/index.ts#L12-L27) if its node version requirements aren't met:
they require v18 or later but we require v20 or later, so the warning looks like this (which is wrong):
```
(node:4619) Warning: Node version must be >=18.0.0 to use this CLI. Current node version: 14.20.0
```
due to this being misleading, we're going to disable this warning entirely. i don't **_think_** we need to emit warnings for mismatched versions of node.js (since the warning is already emitted when users install …
> fix(oclif): disable engine warning

- documentation/commands/openapi.md
- src/commands/openapi/upload.ts
| 🚥 Resolves https://github.com/readmeio/rdme/issues/1330 |
unhides the `--confirm-overwrite` flag. it's a little clunky but it's widely used enough now that we might as well document it.
> fix(openapi/upload): unhide `--confirm-overwrite`

- __tests__/commands/openapi/__snapshots__/upload.test.ts.snap
- __tests__/commands/openapi/upload.test.ts
- src/commands/openapi/upload.ts
| 🚥 Resolves RM-13895 |
fixes a few issues where URLs with no path (e.g., `https://example.com`) or URLs with query params (e.g., `https://example.com/openapi?something=true`) weren't being handled properly.
do tests pass?
> fix(openapi/upload): handle funky URLs

- __tests__/commands/openapi/__snapshots__/upload.test.ts.snap
- __tests__/commands/openapi/upload.test.ts
- src/commands/openapi/upload.ts
| 🚥 Resolves CX-2293 |
we previously had a restriction in place where you could not upload a JSON file (e.g., `petstore.json`) to a slug with a YAML file extension (e.g., `--slug file.yml`). the reasoning was that we didn't want to create any unexpected client-side behaviors and we wanted to prioritize explicitness.
however, we've been getting feedback that it's misleading how `rdme` directs customers towards certain slugs, only to see an error that they can't use that slug due to this file extension restriction.
this PR lifts that restriction and makes it so `rdme` will convert a JSON file to YAML prior to uploading if the slug has a YAML file extension (or vice versa). it will also emit a warning to the user when this happens!
added a bunch of tests for this …
> fix(openapi/upload): better handling for mismatching files/slugs
