readmeio/rdme

lib/help.js
lib/swagger.js
test/swagger.test.js

1. Updated endpoints to reflect API deprecation of Swagger handlers in main Readme app.
2. Minor logic update to success function to pull relevant data and present updated log string.
3. Updated tests to reflect endpoint change.

Next steps after you import a swagger file in the cli

---

cmds/open.js
package-lock.json
package.json

Resolves https://github.com/readmeio/rdme/issues/69

Replacing the opn module with open since it was renamed.

---

action.yml

Seeing this error when publishing to the Marketplace:
Worked on these edits with Sarah!
Fixes RM-3574

docs: update Action metadata

---

src/cmds/openapi.js

Not sure why this promise was written this way but it's weird and I don't like it.

fix: a weirdly written promise

---

documentation/rdme.md

Fixes https://github.com/readmeio/rdme/issues/470

fix(docs): github secrets usage

---

README.md
documentation/legacy-github-action.md
documentation/rdme.md

Per some feedback from Sarah, I expanded on the event trigger stuff a bit since that might not be super clear to folks. I also updated the docs so we're using `actions/checkout@v3`.
Do the docs look good?

docs(GHA): checkout guidance, workflow triggers

---

.github/codeql/config.yml
.github/workflows/codeql-analysis.yml

This adds a config file [per GitHub's docs](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan) so CodeQL ignores our test files.
Does CodeQL pass and do the changes look sound?

ci(CodeQL): add config

---

README.md

| 🚥 Fix RM-1189 |
| :-- |
Adding some long-requested language on the `--2fa` option.

docs: add some language on `--2fa` option

---

__tests__/cmds/openapi/index.test.ts

As part of #577, I noticed an issue with a bunch of our `openapi` command tests where the response from [our `GET /version/{versionId}` endpoint](https://docs.readme.com/reference/getversion) returns a single version object but our mocks incorrectly have them returning an array of objects.
Even worse, the tests were passing just fine because we weren't checking for the version header in subsequent mocks 😬 it should contain a version but that header has always been undefined due to this discrepancy.
This PR cleans up the mess a bit and adds a few stricter mock checks.
Did a quick search and confirmed that this issue is thankfully only affecting this test bed. Do tests pass?

test(`openapi`): fix a few incorrect mocks

---

MAINTAINERS.md

I added a few commands to make it easier to publish releases to GitHub and `npm` (https://github.com/readmeio/rdme/commit/a4998f5121323f9ce9b18f698fee01be90147f7d, https://github.com/readmeio/rdme/commit/e76f69b4c400e08dc84c5dc48fa3563cbd2364ed), so this PR adds some documentation on how to use them.

docs: create MAINTAINERS.md

---

.github/workflows/docs.yml
documentation/github-actions-docs-example.md
documentation/github-actions-openapi-example.md
documentation/legacy-github-action.md
documentation/rdme.md

Updates docs categories/versions to reflect docs migration effort.

docs: update version/category to reflect new location

---

package-lock.json

Before:
```
Package        Current  Wanted  Latest  Location                    Depended by
@types/jest     29.2.4  29.2.5  29.2.5  node_modules/@types/jest    rdme
ajv             8.11.2  8.12.0  8.12.0  node_modules/ajv            rdme
chalk            4.1.2   4.1.2   5.2.0  node_modules/chalk          rdme
ci-info          3.7.0   3.7.1   3.7.1  node_modules/ci-info        rdme
configstore      5.0.1   5.0.1   6.0.0  node_modules/configstore    rdme
eslint          8.30.0  8.31.0  8.31.0  node_modules/eslint         rdme
ignore           5.2.1   5.2.4   5.2.4  node_modules/ignore         rdme
jest-extended    3.2.0   3.2.1   3.2.1  node_modules/jest-extended  rdme
node-fetch       2.6.7   2.6.7   3.3.0  node_modules/node-fetch     rdme
ora              5.4.1   5.4.1   6.1.2 …
```

chore(deps): bump a bunch of deps

---

package-lock.json
package.json

Before:
```
Package                Current  Wanted  Latest  Location                            Depended by
@commitlint/cli         17.5.0  17.5.1  17.5.1  node_modules/@commitlint/cli        rdme
@readme/eslint-config   10.5.1  10.5.2  10.5.2  node_modules/@readme/eslint-config  rdme
@types/node-fetch        2.6.2   2.6.3   2.6.3  node_modules/@types/node-fetch      rdme
@types/prompts           2.4.3   2.4.4   2.4.4  node_modules/@types/prompts         rdme
chalk                    4.1.2   4.1.2   5.2.0  node_modules/chalk                  rdme
configstore              5.0.1   5.0.1   6.0.0  node_modules/configstore            rdme
eslint                  8.36.0  8.37.0  8.37.0  node_modules/eslint                 rdme
node-fetch               2.6.9   2.6.9   3.3.1 …
```

chore(deps): bump

---

README.md

Describe in detail what this PR is for.

docs: update README with `v9` callout

---

__tests__/helpers/github-workflow-schema.json
bin/json-schema-store.js
package-lock.json
package.json

Before:
```
Package                Current  Wanted  Latest  Location                            Depended by
@readme/eslint-config   13.4.0  13.4.1  13.4.1  node_modules/@readme/eslint-config  rdme
@rollup/plugin-json      6.0.1   6.1.0   6.1.0  node_modules/@rollup/plugin-json    rdme
@vitest/coverage-v8      1.1.0   1.1.1   1.1.1  node_modules/@vitest/coverage-v8    rdme
@vitest/expect           1.1.0   1.1.1   1.1.1  node_modules/@vitest/expect         rdme
eslint                  8.55.0  8.56.0  8.56.0  node_modules/eslint                 rdme
knip                     3.4.0  3.10.0  3.10.0  node_modules/knip                   rdme
msw                     2.0.10  2.0.11  2.0.11  node_modules/msw                    rdme
open                     9.1.0   9.1.0  10.0.2  node_modules/open …
```

chore(deps): npm up

---

LICENSE

Happy New Year 🥳
| 🚥 Resolves Time Travel |
Bump the copyright date.
Unless this is a load bearing text file, everything should be just fine.

fix: Update LICENSE for 2024

---

package-lock.json

Before:
```
Package                                        Current          Wanted  Latest  Location                                             Depended by
@commitlint/cli                                 19.5.0          19.6.0  19.6.0  node_modules/@commitlint/cli                         rdme
@commitlint/config-conventional                 19.5.0          19.6.0  19.6.0  node_modules/@commitlint/config-conventional         rdme
@oclif/core                                     4.0.32          4.0.34  4.0.34  node_modules/@oclif/core                             rdme
@oclif/plugin-autocomplete                       3.2.8          3.2.11  3.2.11  node_modules/@oclif/plugin-autocomplete              rdme
@oclif/plugin-help …
```

chore(deps): `npm up`

---

documentation/commands/openapi.md
src/commands/openapi/convert.ts
src/commands/openapi/index.ts
src/commands/openapi/inspect.ts
src/commands/openapi/reduce.ts
src/commands/openapi/validate.ts
src/lib/flags.ts
src/lib/logger.ts
src/lib/readmeAPIFetch.ts

cherry picks a few refactors from https://github.com/readmeio/rdme/pull/1116 to minimize that diff and bring these changes to the v9 channel
do tests still pass?

fix: openapi arg doc enhancements, refactors

---

documentation/migration-guide.md
tsconfig.json

fixing up a few oversights that fell through the cracks! will backport these changes to v9 once this is merged.

docs: migration guide tweaks

---

.github/workflows/docs.yml
documentation/legacy/github-actions-docs-example.md
documentation/legacy/github-actions-openapi-example.md
documentation/legacy/legacy-github-action.md
documentation/legacy/rdme.md

Ok take 2 updating the docs syncing command! Turns out I had a really out of date version locally, so it was easier just to make a new branch instead of trying to squash a bunch of merge conflicts. 
This updates the docs syncing to use the new version of rdme now that our main docs project is on Refactored. 

ci: update `docs upload` owlfooding

---

__tests__/helpers/github-workflow-schema.json
package-lock.json
package.json

before:
```
Package                  Current   Wanted   Latest  Location                              Depended by
@oclif/plugin-not-found   3.2.47   3.2.48   3.2.48  node_modules/@oclif/plugin-not-found  rdme
@types/semver              7.5.8    7.7.0    7.7.0  node_modules/@types/semver            rdme
@types/validator         13.12.2  13.12.3  13.12.3  node_modules/@types/validator         rdme
@vitest/coverage-v8        3.0.9    3.1.1    3.1.1  node_modules/@vitest/coverage-v8      rdme
@vitest/expect             3.0.9    3.1.1    3.1.1  node_modules/@vitest/expect           rdme
eslint                    8.57.1   8.57.1   9.23.0  node_modules/eslint                   rdme
knip                      5.46.0   5.46.4   5.46.4  node_modules/knip                     rdme
mime-types …
```

chore(deps/v9): bump

---

documentation/commands/docs.md

i've changed my mind lol, it'll still be good to have this doc for support purposes! but i made a few tweaks so the risk is clearly conveyed to folks

docs: whoops bring this doc back, but with a callout

---

package-lock.json
package.json
src/lib/hooks/createGHA.ts

adds initial support for `rdme` plugins. not going to write any further docs on this for the time being. more context can be found [here](https://readmeio.slack.com/archives/C08NTUB6XPB/p1744826658541339).

feat(cli): add support for plugins

---

src/lib/readmeAPIFetch.ts

widens the types of these util functions a bit so they play more nicely with plugins.
i confirmed locally that these types play nicely with plugins.

fix: fetch util types

---

src/lib/types/openapiDoc.ts

Updates our OpenAPI schema with some new additions and revisions to our public API.

chore: updating our openapi schema

---

__tests__/commands/docs/__snapshots__/migrate.test.ts.snap
__tests__/commands/docs/migrate.test.ts
src/commands/docs/migrate.ts
src/index.ts
src/lib/readPage.ts
src/lib/readmeAPIFetch.ts
src/lib/syncDocsPath.legacy.ts
src/lib/syncPagePath.ts

fixes RM-12513
experimental alpha, not ready for public usage just yet.
i added a tiny bit of test coverage, will eventually want to look into how to test this using plugins.

feat: add `docs migrate` command

---

src/lib/baseCommand.ts
src/lib/readmeAPIFetch.ts
src/types.ts

smol type tweaks to https://github.com/readmeio/rdme/pull/1221

refactor: smol type enhancements

---

src/lib/types/openapiDoc.ts

Updates our OpenAPI definition with the latest new endpoints and property additions.

chore: updating our OpenAPI definition

---

documentation/migration-guide.md
package-lock.json

`npm outdated` before:
```
Package                                 Current  Wanted  Latest  Location                                             Depended by
@oclif/core                               4.3.3   4.4.0   4.4.0  node_modules/@oclif/core                             rdme
@oclif/plugin-autocomplete               3.2.30  3.2.31  3.2.31  node_modules/@oclif/plugin-autocomplete              rdme
@oclif/plugin-plugins                    5.4.41  5.4.42  5.4.42  node_modules/@oclif/plugin-plugins                   rdme
@oclif/plugin-warn-if-update-available   3.1.41  3.1.42  3.1.42  node_modules/@oclif/plugin-warn-if-update-available  rdme
@rollup/plugin-commonjs                  28.0.5  28.0.6  28.0.6  node_modules/@rollup/plugin-commonjs                 rdme
@vitest/coverage-v8 …
```

chore(deps): updating out of date dependencies
